//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString;

@interface _YYTextViewUndoObject : NSObject
{
    NSAttributedString *_text;
    struct _NSRange _selectedRange;
}

+ (id)objectWithText:(id)arg1 range:(struct _NSRange)arg2;
@property(nonatomic) struct _NSRange selectedRange; // @synthesize selectedRange=_selectedRange;
@property(retain, nonatomic) NSAttributedString *text; // @synthesize text=_text;
- (void).cxx_destruct;

@end

