//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AidStorage : NSObject
{
}

+ (void)cleanAid:(id)arg1;
+ (double)aidGenTime:(id)arg1;
+ (id)aidValue:(id)arg1;
+ (void)setAid:(id)arg1 appName:(id)arg2;
+ (void)initialize;
+ (id)instance;

@end

