//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LKDBModel.h"

@class AlbumDetail_Image, NSString;

@interface AlbumLatest_Video : LKDBModel
{
    long long _AlbumLatest_VideoId;
    long long _number;
    NSString *_section;
    NSString *_title;
    AlbumDetail_Image *_image;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) AlbumDetail_Image *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *section; // @synthesize section=_section;
@property(nonatomic) long long number; // @synthesize number=_number;
@property(nonatomic) long long AlbumLatest_VideoId; // @synthesize AlbumLatest_VideoId=_AlbumLatest_VideoId;
- (void).cxx_destruct;

@end

