//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, CMMotionManager, NSNumber, NSString;

@interface ALDeviceInfo : NSObject <CLLocationManagerDelegate>
{
    NSNumber *_netWorkState;
    CLLocationManager *_locManager;
    double _magneticHeading;
    double _gravityX;
    double _gravityY;
    double _gravityZ;
    CMMotionManager *_motionManager;
}

+ (id)freeDiskSpace;
+ (id)totalDiskSpace;
+ (id)GetCurrentDeviceModel;
+ (id)getWifiName;
+ (id)dictionaryToJson:(id)arg1;
+ (id)shareManager;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(nonatomic) double gravityZ; // @synthesize gravityZ=_gravityZ;
@property(nonatomic) double gravityY; // @synthesize gravityY=_gravityY;
@property(nonatomic) double gravityX; // @synthesize gravityX=_gravityX;
@property(nonatomic) double magneticHeading; // @synthesize magneticHeading=_magneticHeading;
@property(retain, nonatomic) CLLocationManager *locManager; // @synthesize locManager=_locManager;
@property(retain, nonatomic) NSNumber *netWorkState; // @synthesize netWorkState=_netWorkState;
- (void).cxx_destruct;
- (id)getSystemVersion;
- (id)getMacAddress;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (id)getNetWorkStates;
- (id)fetchJsonInfo;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

