//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"

@class NSString;

@interface APIRequestManager : NSObject <NSURLSessionDelegate>
{
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
}

+ (id)defaultAPIManager;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)postRequestWithPath:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getRequestWithPath:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)assemblingParams:(id)arg1;
- (void)requestSplashApiWithParams:(id)arg1 callBackSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestPvStatisticsApiWithPath:(id)arg1 callBackSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestClickStatisticsApiWithPath:(id)arg1 callBackSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestInfoFlowApiWithParams:(id)arg1 callBackSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestSpotApiWithParams:(id)arg1 callBackSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

