//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AppMonitorEventServiceDelegate.h"

@class NSLock, NSMutableDictionary, NSString;

@interface AppMonitorSdkAdapter : NSObject <AppMonitorEventServiceDelegate>
{
    NSMutableDictionary *_eventDict;
    NSLock *_lock;
    NSMutableDictionary *_eventCounter;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *eventCounter; // @synthesize eventCounter=_eventCounter;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *eventDict; // @synthesize eventDict=_eventDict;
- (void).cxx_destruct;
- (void)addLogInSdk:(id)arg1 rawPoint:(_Bool)arg2;
- (void)uploadEventForEventId:(id)arg1;
- (void)parseRawEvent:(id)arg1;
- (void)sendRawEvent:(id)arg1;
- (id)uploadEvent:(id)arg1 event:(id)arg2 rawPoint:(_Bool)arg3;
- (id)getEventForUTDimensionValueSet:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3 extraInfo:(id)arg4;
- (id)getDictionaryForUploadEvnetnWithId:(id)arg1;
- (long long)getEventCountForId:(id)arg1;
- (void)mark:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

