//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorEvent.h"

#import "AppMonitorRawEventProtocol.h"

@class NSString;

@interface AppMonitorRawAlarmEvent : AppMonitorEvent <AppMonitorRawEventProtocol>
{
    long long _successCount;
    long long _failCount;
    NSString *_errorCode;
    NSString *_errorMsg;
}

+ (id)parseRawUTMsg:(id)arg1;
@property(retain, nonatomic) NSString *errorMsg; // @synthesize errorMsg=_errorMsg;
@property(retain, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) long long failCount; // @synthesize failCount=_failCount;
@property(nonatomic) long long successCount; // @synthesize successCount=_successCount;
- (void).cxx_destruct;
- (id)dumpToUTEvent;
- (void)setFailWithErrorCode:(id)arg1 errorMsg:(id)arg2;
- (void)setSuccess;
- (id)initWithEventId:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

