//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdBaseNativeAdView.h"

@interface BaiduMobAdPrerollNativeView : BaiduMobAdBaseNativeAdView
{
}

- (void)checkVisible;
- (void)loadAndDisplayAdWithObject:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1 videoView:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 mainImage:(id)arg2;

@end

