//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDelegate.h"

@class BaiduMobAdURLConnection, NSString, NSTimer, UIWebView;

@interface BaiduMobAdAjaxAgent : NSObject <NSURLConnectionDelegate>
{
    UIWebView *_webView;
    NSTimer *_timer;
    BaiduMobAdURLConnection *_connection;
    NSString *_onSuccess;
    NSString *_onfailure;
    NSString *_onTimeout;
}

@property(copy, nonatomic) NSString *onTimeout; // @synthesize onTimeout=_onTimeout;
@property(copy, nonatomic) NSString *onfailure; // @synthesize onfailure=_onfailure;
@property(copy, nonatomic) NSString *onSuccess; // @synthesize onSuccess=_onSuccess;
@property(retain, nonatomic) BaiduMobAdURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void)cancelURLConnection;
- (void)nativeFireEvent:(id)arg1 str:(id)arg2;
- (void)requestTimeout;
- (void)onRequestAdFail:(id)arg1 requestInfo:(id)arg2;
- (void)onRequestAdSuccess:(id)arg1 requestInfo:(id)arg2;
- (void)asyncRequest:(id)arg1 timeout:(double)arg2 onSuccess:(id)arg3 onFailure:(id)arg4 onTimeout:(id)arg5 forWebView:(id)arg6;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

