//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SFSafariViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class BaiduMobAdInstance, BaiduMobAdVideoLpRenderer, NSString;

@interface BaiduMobAdSFViewController : SFSafariViewController <UIGestureRecognizerDelegate>
{
    _Bool _supportVideoLP;
    _Bool _first;
    id <BaiduMobAdSFDelegate> _sfDelegate;
    BaiduMobAdInstance *_instance;
    BaiduMobAdVideoLpRenderer *_renderer;
}

@property _Bool first; // @synthesize first=_first;
@property(retain, nonatomic) BaiduMobAdVideoLpRenderer *renderer; // @synthesize renderer=_renderer;
@property(retain, nonatomic) BaiduMobAdInstance *instance; // @synthesize instance=_instance;
@property(nonatomic) _Bool supportVideoLP; // @synthesize supportVideoLP=_supportVideoLP;
@property(nonatomic) id <BaiduMobAdSFDelegate> sfDelegate; // @synthesize sfDelegate=_sfDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

