//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdHTMLRenderer.h"

#import "BaiduMobAdWebViewDelegate.h"

@class BaiduMobAdWebView, NSString, NSURL;

@interface BaiduMobAdH5Renderer : BaiduMobAdHTMLRenderer <BaiduMobAdWebViewDelegate>
{
    _Bool _needSendShowLog;
    _Bool _isWebViewPrepared;
    _Bool _supportShutDown;
    NSString *_htmlString;
    BaiduMobAdWebView *_adWebView;
    NSURL *_firstUrl;
}

@property(retain, nonatomic) NSURL *firstUrl; // @synthesize firstUrl=_firstUrl;
@property(nonatomic) _Bool supportShutDown; // @synthesize supportShutDown=_supportShutDown;
@property(retain, nonatomic) BaiduMobAdWebView *adWebView; // @synthesize adWebView=_adWebView;
@property(nonatomic) _Bool isWebViewPrepared; // @synthesize isWebViewPrepared=_isWebViewPrepared;
@property(nonatomic) _Bool needSendShowLog; // @synthesize needSendShowLog=_needSendShowLog;
@property(copy, nonatomic) NSString *htmlString; // @synthesize htmlString=_htmlString;
- (void)evalScript:(id)arg1;
- (void)dealloc;
- (id)adView;
- (void)dismissSplash;
- (void)timeAnimation;
- (void)setRemainTime;
- (void)bdWebViewDidStartLoad:(id)arg1;
- (void)bdWebViewDidFinishLoad:(id)arg1;
- (void)bdWebView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)bdWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

