//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdMraidBridge.h"

@interface BaiduMobAdH5Bridge : BaiduMobAdMraidBridge
{
}

- (void)didFinishWithResult:(id)arg1;
- (void)setActionUrl:(id)arg1;

@end

