//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCAuth, BCEAppEntity, NSDictionary, NSString;

@interface BCEAppClient : NSObject
{
    NSDictionary *permissions;
    NSString *_userId;
    NSString *_companyId;
    BCEAppEntity *_app;
    BCAuth *_appAuth;
}

+ (void)clearAllClient;
+ (id)getClient:(id)arg1;
+ (void)unregisterClient:(id)arg1;
+ (void)registerClient:(id)arg1 client:(id)arg2;
@property(retain, nonatomic) BCAuth *appAuth; // @synthesize appAuth=_appAuth;
@property(retain, nonatomic) BCEAppEntity *app; // @synthesize app=_app;
@property(retain, nonatomic) NSString *companyId; // @synthesize companyId=_companyId;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSDictionary *permissions; // @synthesize permissions;
- (void).cxx_destruct;
- (id)getHttpCallUrl:(id)arg1 withParams:(id)arg2;
- (id)getCallbackForWeb;
- (void)addPermission:(id)arg1;
- (_Bool)hasPermission:(id)arg1;
- (id)initWithApp:(id)arg1 userId:(id)arg2 companyId:(id)arg3;

@end

