//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface BCHandlerResult : NSObject
{
    int _retCode;
    NSString *_strCode;
    NSDictionary *_retResult;
}

+ (id)resultFromCode:(int)arg1;
+ (id)resultFromCode:(int)arg1 result:(id)arg2;
+ (id)resultFromCode:(int)arg1 result:(id)arg2 strCode:(id)arg3;
@property(retain, nonatomic) NSDictionary *retResult; // @synthesize retResult=_retResult;
@property(nonatomic) int retCode; // @synthesize retCode=_retCode;
@property(retain, nonatomic) NSString *strCode; // @synthesize strCode=_strCode;
- (void).cxx_destruct;

@end

