//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKStoreProductViewControllerDelegate.h"

@class CSCustomStoreVC, NSString;

@interface CSAppStoreObject : NSObject <SKStoreProductViewControllerDelegate>
{
    _Bool _isValid;
    CDUnknownBlockType _blockShowFinished;
    CDUnknownBlockType _blockWillClose;
    CDUnknownBlockType _blockCloseFinished;
    CSCustomStoreVC *_appStoreVC;
}

@property(retain, nonatomic) CSCustomStoreVC *appStoreVC; // @synthesize appStoreVC=_appStoreVC;
@property(readonly, nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(copy, nonatomic) CDUnknownBlockType blockCloseFinished; // @synthesize blockCloseFinished=_blockCloseFinished;
@property(copy, nonatomic) CDUnknownBlockType blockWillClose; // @synthesize blockWillClose=_blockWillClose;
@property(copy, nonatomic) CDUnknownBlockType blockShowFinished; // @synthesize blockShowFinished=_blockShowFinished;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (_Bool)showFrom:(id)arg1;
- (id)initWithiTunesUrl:(id)arg1;
- (id)initWithAppID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

