//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSError, CSInterstitialView, NSError, NSString;

@protocol CSInterstitialViewDelegate <NSObject>
- (void)csInterstitialView:(CSInterstitialView *)arg1 downloadVideoFailure:(NSError *)arg2;
- (void)csInterstitialViewDownloadVideoSuccess:(CSInterstitialView *)arg1;
- (void)csInterstitialViewStartDownloadVideo:(CSInterstitialView *)arg1;
- (void)csInterstitialView:(CSInterstitialView *)arg1 sendShowLogWithParams:(NSString *)arg2;
- (void)csInterstitialViewClickCloseButton:(CSInterstitialView *)arg1;
- (void)csInterstitialView:(CSInterstitialView *)arg1 clickedWithUrl:(NSString *)arg2 andEventParams:(NSString *)arg3;
- (void)csInterstitialViewCountDownFinished:(CSInterstitialView *)arg1;
- (void)csInterstitialView:(CSInterstitialView *)arg1 loadFailure:(CSError *)arg2;
- (void)csInterstitialViewLoadSuccess:(CSInterstitialView *)arg1;
- (unsigned int)csInterstitialViewGetStatus:(CSInterstitialView *)arg1;
@end

