//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSAppStoreManagerDelegate.h"
#import "CSInteractiveVCDelegate.h"

@class CSNativeFeedsItem, NSArray, NSMutableArray, NSString, UIButton, UIControl, UILabel, UIViewController, UIWebView;

@interface CSNativeFeedsView : UIView <CSInteractiveVCDelegate, CSAppStoreManagerDelegate>
{
    _Bool _finishIcon;
    CSNativeFeedsItem *_nativeFeedsItem;
    UIViewController *_rootViewController;
    UILabel *_labelTitle;
    UILabel *_labelContent;
    UILabel *_labelConfirm;
    UIButton *_buttonConfirm;
    UIButton *_buttonCancel;
    UIControl *_ctrlBG;
    UIWebView *_webViewIcon;
    NSArray *_webViewPictures;
    NSString *_fileNameIcon;
    NSString *_filePathIcon;
    NSMutableArray *_marrFinishPicture;
    UIControl *_ctrlConfirmBG;
}

@property(retain, nonatomic) UIControl *ctrlConfirmBG; // @synthesize ctrlConfirmBG=_ctrlConfirmBG;
@property(retain, nonatomic) NSMutableArray *marrFinishPicture; // @synthesize marrFinishPicture=_marrFinishPicture;
@property(nonatomic) _Bool finishIcon; // @synthesize finishIcon=_finishIcon;
@property(retain, nonatomic) NSString *filePathIcon; // @synthesize filePathIcon=_filePathIcon;
@property(retain, nonatomic) NSString *fileNameIcon; // @synthesize fileNameIcon=_fileNameIcon;
@property(retain, nonatomic) NSArray *webViewPictures; // @synthesize webViewPictures=_webViewPictures;
@property(retain, nonatomic) UIWebView *webViewIcon; // @synthesize webViewIcon=_webViewIcon;
@property(retain, nonatomic) UIControl *ctrlBG; // @synthesize ctrlBG=_ctrlBG;
@property(retain, nonatomic) UIButton *buttonCancel; // @synthesize buttonCancel=_buttonCancel;
@property(retain, nonatomic) UIButton *buttonConfirm; // @synthesize buttonConfirm=_buttonConfirm;
@property(retain, nonatomic) UILabel *labelConfirm; // @synthesize labelConfirm=_labelConfirm;
@property(retain, nonatomic) UILabel *labelContent; // @synthesize labelContent=_labelContent;
@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) CSNativeFeedsItem *nativeFeedsItem; // @synthesize nativeFeedsItem=_nativeFeedsItem;
- (void).cxx_destruct;
- (void)csAppStoreManagerPageClose;
- (void)csAppStoreManagerPageShow;
- (void)csInteractiveVCClose:(id)arg1;
- (void)loadFinished;
- (void)showPicture:(id)arg1;
- (void)showIcon;
- (void)clickADCancel;
- (void)clickADConfirm;
- (void)clickAD;
- (void)showAD;
@property(readonly, nonatomic) NSArray *pictureSizes;
@property(readonly, nonatomic) NSArray *pictureViews;
@property(readonly, nonatomic) struct CGSize iconSize;
@property(readonly, nonatomic) UIView *iconView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andNativeFeedsItem:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

