//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVPlayerItem, AVPlayerLayer, CSSplashAdItem, CSVideoADCoinView, UIButton;

@interface CSSplashAdVideoView : UIView
{
    _Bool _playCache;
    _Bool _mute;
    unsigned int _videoADState;
    id <CSSplashAdVideoViewDelegate> _delegate;
    AVPlayerItem *_avPlayerItem;
    UIButton *_buttonMute;
    CSVideoADCoinView *_countdownView;
    CSSplashAdItem *_splashADItem;
    AVPlayerLayer *_avPlayerLayer;
}

@property(nonatomic) unsigned int videoADState; // @synthesize videoADState=_videoADState;
@property(retain, nonatomic) AVPlayerLayer *avPlayerLayer; // @synthesize avPlayerLayer=_avPlayerLayer;
@property(retain, nonatomic) CSSplashAdItem *splashADItem; // @synthesize splashADItem=_splashADItem;
@property(retain, nonatomic) CSVideoADCoinView *countdownView; // @synthesize countdownView=_countdownView;
@property(nonatomic) _Bool mute; // @synthesize mute=_mute;
@property(retain, nonatomic) UIButton *buttonMute; // @synthesize buttonMute=_buttonMute;
@property(retain, nonatomic) AVPlayerItem *avPlayerItem; // @synthesize avPlayerItem=_avPlayerItem;
@property(nonatomic) _Bool playCache; // @synthesize playCache=_playCache;
@property(nonatomic) __weak id <CSSplashAdVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)clickMute;
- (void)notifAVPlayerItemDidPlayToEndTime:(id)arg1;
- (void)notifAppDidBecomeActive:(id)arg1;
- (void)notifAppWillResignActive:(id)arg1;
- (void)exitPlay;
- (void)playVideoRealFinished:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)playSplashVideoWithFilePathForDelay:(id)arg1;
- (void)playSplashVideoWithFilePath:(id)arg1;
- (void)loadSplashVideoError:(id)arg1;
- (void)readyPlaySplashVideoAD;
- (void)showSplashVideoInfo:(id)arg1;
- (void)cancelSplashVideoAD;
- (void)layoutSubviews:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)init;

@end

