//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSSplashView, NSString, UIViewController;

@interface CSSplashAd : NSObject
{
    int _minShowDur;
    int _minAutoCloseDur;
    NSString *_placementID;
    UIViewController *_rootViewController;
    id <CSSplashAdDelegate> _delegate;
    CSSplashView *_splashView;
}

+ (id)sharedInstance;
@property(retain, nonatomic) CSSplashView *splashView; // @synthesize splashView=_splashView;
@property(nonatomic) __weak id <CSSplashAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) int minAutoCloseDur; // @synthesize minAutoCloseDur=_minAutoCloseDur;
@property(nonatomic) int minShowDur; // @synthesize minShowDur=_minShowDur;
@property(copy, nonatomic) NSString *placementID; // @synthesize placementID=_placementID;
- (void).cxx_destruct;
- (_Bool)showSplashInWindow:(id)arg1 andDownloadVideoOnlyWifi:(_Bool)arg2;
- (id)init;

@end

