//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSVideoADManager, NSString, UIViewController;

@interface CSVideoAD : NSObject
{
    _Bool _hideCoinLabel;
    _Bool _rewardMode;
    NSString *_placementID;
    NSString *_userInfo;
    UIViewController *_rootViewController;
    id <CSVideoADDelegate> _delegate;
    CSVideoADManager *_videoADManager;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool rewardMode; // @synthesize rewardMode=_rewardMode;
@property(retain, nonatomic) CSVideoADManager *videoADManager; // @synthesize videoADManager=_videoADManager;
@property(nonatomic) __weak id <CSVideoADDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(copy, nonatomic) NSString *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool hideCoinLabel; // @synthesize hideCoinLabel=_hideCoinLabel;
@property(copy, nonatomic) NSString *placementID; // @synthesize placementID=_placementID;
- (void).cxx_destruct;
- (void)receiveResultOfQuery:(id)arg1;
- (void)queryCoins:(CDUnknownBlockType)arg1;
- (void)showVideoADWithOrientation:(_Bool)arg1;
- (void)loadVideoADWithOrientation:(_Bool)arg1 andDownloadVideoOnlyWifi:(_Bool)arg2;
- (void)checkVideoAD;
@property(readonly, nonatomic) unsigned int videoStatus;
- (id)init;

@end

