//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class DRAgentRedVideoModel, UIButton, UILabel;

@interface DRAgentPlayerControlView : UIImageView
{
    id <DRAgentScrollImageViewDelegate> _delegate;
    DRAgentRedVideoModel *_videoModel;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
    UIButton *_repeatButton;
}

@property(retain, nonatomic) UIButton *repeatButton; // @synthesize repeatButton=_repeatButton;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) DRAgentRedVideoModel *videoModel; // @synthesize videoModel=_videoModel;
@property(nonatomic) __weak id <DRAgentScrollImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)drawRadialGradient:(struct CGContext *)arg1 path:(struct CGPath *)arg2 startColor:(struct CGColor *)arg3 endColor:(struct CGColor *)arg4;
- (void)buttonClick:(id)arg1;
- (void)downClick;
- (void)setRepeatButtonHidden:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

