//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DRAgentSplash, NSArray, NSError, UIImage;

@protocol DRAgentSplashAdDelegate <NSObject>

@optional
- (void)adSplashStoreProductViewControllerReturn:(DRAgentSplash *)arg1;
- (void)adSplashWebViewReturn:(DRAgentSplash *)arg1;
- (void)adSplashscreenDismiss:(DRAgentSplash *)arg1;
- (void)adSplashDidClick:(DRAgentSplash *)arg1 adverType:(long long)arg2;
- (void)adSplashShowed:(DRAgentSplash *)arg1 adverType:(long long)arg2 didFailToReceiveAdWithError:(NSError *)arg3;
- (void)adSplashshowed:(DRAgentSplash *)arg1 adverType:(long long)arg2;
- (void)adSplash:(DRAgentSplash *)arg1 didFailToReceiveAdWithError:(NSError *)arg2;
- (void)adSplashDidFinishLoading:(DRAgentSplash *)arg1 adverType:(long long)arg2;
- (UIImage *)adSplashbackgroundImage:(DRAgentSplash *)arg1;
- (NSArray *)adSplashSubViews:(DRAgentSplash *)arg1;
@end

