//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DRAgentAVPlayer;

@protocol DRAgentAVPlayerDelegate <NSObject>

@optional
- (void)promptPlayer:(DRAgentAVPlayer *)arg1 statusOrErrorWith:(long long)arg2;
- (void)refreshDataWith:(double)arg1 Progress:(double)arg2 LoadRange:(double)arg3;
@end

