//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface DRAgentMediaDownloaderStatus : NSObject
{
    NSMutableSet *_downloadingURLS;
}

+ (id)shared;
@property(retain, nonatomic) NSMutableSet *downloadingURLS; // @synthesize downloadingURLS=_downloadingURLS;
- (void).cxx_destruct;
- (id)urls;
- (_Bool)containsURL:(id)arg1;
- (void)removeURL:(id)arg1;
- (void)addURL:(id)arg1;

@end

