//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DRAgentActionWorkerDelegate.h"

@class DRAgentActionWorker, DRAgentContentInfo, DRAgentMediaCacheWorker, NSString, NSURL, NSURLSessionDataTask;

@interface DRAgentMediaDownloader : NSObject <DRAgentActionWorkerDelegate>
{
    _Bool _saveToCache;
    _Bool _downloadToEnd;
    NSURL *_url;
    id <DRAgentMediaDownloaderDelegate> _delegate;
    DRAgentContentInfo *_info;
    NSURLSessionDataTask *_task;
    DRAgentMediaCacheWorker *_cacheWorker;
    DRAgentActionWorker *_actionWorker;
}

@property(nonatomic) _Bool downloadToEnd; // @synthesize downloadToEnd=_downloadToEnd;
@property(retain, nonatomic) DRAgentActionWorker *actionWorker; // @synthesize actionWorker=_actionWorker;
@property(retain, nonatomic) DRAgentMediaCacheWorker *cacheWorker; // @synthesize cacheWorker=_cacheWorker;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(nonatomic) _Bool saveToCache; // @synthesize saveToCache=_saveToCache;
@property(retain, nonatomic) DRAgentContentInfo *info; // @synthesize info=_info;
@property(nonatomic) __weak id <DRAgentMediaDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)actionWorker:(id)arg1 didFinishWithError:(id)arg2;
- (void)actionWorker:(id)arg1 didReceiveData:(id)arg2 isLocal:(_Bool)arg3;
- (void)actionWorker:(id)arg1 didReceiveResponse:(id)arg2;
- (void)cancel;
- (void)downloadFromStartToEnd;
- (void)downloadTaskFromOffset:(unsigned long long)arg1 length:(unsigned long long)arg2 toEnd:(_Bool)arg3;
- (id)initWithURL:(id)arg1 cacheWorker:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

