//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DRAgentMediaDownloader, NSData, NSError, NSURLResponse;

@protocol DRAgentMediaDownloaderDelegate <NSObject>

@optional
- (void)mediaDownloader:(DRAgentMediaDownloader *)arg1 didFinishedWithError:(NSError *)arg2;
- (void)mediaDownloader:(DRAgentMediaDownloader *)arg1 didReceiveData:(NSData *)arg2;
- (void)mediaDownloader:(DRAgentMediaDownloader *)arg1 didReceiveResponse:(NSURLResponse *)arg2;
@end

