//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GDT_Argument : NSObject
{
    unsigned char _urlEncode;
    unsigned char _isRequired;
    NSString *_key;
    NSString *_value;
}

@property(nonatomic) unsigned char isRequired; // @synthesize isRequired=_isRequired;
@property(nonatomic) unsigned char urlEncode; // @synthesize urlEncode=_urlEncode;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

