//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDT_OfflineCache : NSObject
{
    long long _length;
    long long _queueExpirationSecs;
    long long _timeout;
}

@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(nonatomic) long long queueExpirationSecs; // @synthesize queueExpirationSecs=_queueExpirationSecs;
@property(nonatomic) long long length; // @synthesize length=_length;

@end

