//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface GDTAppSettings : NSObject
{
    NSMutableDictionary *_data;
}

@property(retain) NSMutableDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)placementObjectForKey:(id)arg1 placementId:(id)arg2;
- (void)setPlacementObject:(id)arg1 ForKey:(id)arg2 placementId:(id)arg3;
- (void)setAppObject:(id)arg1 ForKey:(id)arg2;
- (id)appObjectForKey:(id)arg1;
- (id)init;

@end

