//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class GDTVAMonitorConfig, GDTVAMonitorTimeline, NSDictionary, NSString, UIView;

@interface GDTVAMonitor : NSObject <NSCoding>
{
    _Bool _canMeasurable;
    _Bool _isValid;
    _Bool _isVideo;
    UIView *_adView;
    NSString *_url;
    NSString *_redirectURL;
    NSString *_impressionID;
    NSString *_adID;
    NSString *_domain;
    NSString *_edid;
    GDTVAMonitorTimeline *_timeline;
    unsigned long long _status;
    unsigned long long _progressStatus;
    GDTVAMonitorConfig *_config;
    id <GDTVAMonitorDataProtocol> _delegate;
    NSDictionary *_keyValueAccess;
    unsigned long long _progressTypeNeedTrack;
}

+ (id)monitorWithView:(id)arg1 isVideo:(_Bool)arg2 url:(id)arg3 redirectURL:(id)arg4 impressionID:(id)arg5 adID:(id)arg6 keyValueAccess:(id)arg7 config:(id)arg8 domain:(id)arg9 edid:(id)arg10;
@property(nonatomic) unsigned long long progressTypeNeedTrack; // @synthesize progressTypeNeedTrack=_progressTypeNeedTrack;
@property(retain, nonatomic) NSDictionary *keyValueAccess; // @synthesize keyValueAccess=_keyValueAccess;
@property(nonatomic) __weak id <GDTVAMonitorDataProtocol> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) _Bool isVideo; // @synthesize isVideo=_isVideo;
@property(readonly, nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(readonly, nonatomic) GDTVAMonitorConfig *config; // @synthesize config=_config;
@property(nonatomic) unsigned long long progressStatus; // @synthesize progressStatus=_progressStatus;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(readonly, nonatomic) GDTVAMonitorTimeline *timeline; // @synthesize timeline=_timeline;
@property(readonly, copy, nonatomic) NSString *edid; // @synthesize edid=_edid;
@property(readonly, copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(readonly, copy, nonatomic) NSString *adID; // @synthesize adID=_adID;
@property(readonly, copy, nonatomic) NSString *impressionID; // @synthesize impressionID=_impressionID;
@property(readonly, copy, nonatomic) NSString *redirectURL; // @synthesize redirectURL=_redirectURL;
@property(readonly, copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, nonatomic) __weak UIView *adView; // @synthesize adView=_adView;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)generateUpload;
- (_Bool)canRecord:(id)arg1;
- (id)keyQuery:(id)arg1;
- (void)verifyExpose;
- (void)verifyProgress;
- (void)captureAdStatus;
- (void)stopAndUpload;
- (void)captureAdStatusAndVerify;
- (id)initWithView:(id)arg1 isVideo:(_Bool)arg2 url:(id)arg3 redirectURL:(id)arg4 impressionID:(id)arg5 adID:(id)arg6 keyValueAccess:(id)arg7 config:(id)arg8 domain:(id)arg9 edid:(id)arg10;

@end

