//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface IJKSDLHudViewCell : UITableViewCell
{
    UILabel *_column[2];
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setHudValue:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

