//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

@class IMAdsConfigRendering_SaveContentModel, IMAdsConfig_WebviewMode, NSNumber<IMOptional>;

@interface IMAdsConfigRenderingModel : IMJSONModel
{
    _Bool _shouldRenderPopup;
    long long _renderTimeout;
    long long _picWidth;
    long long _picHeight;
    long long _picQuality;
    IMAdsConfigRendering_SaveContentModel *_savecontent;
    IMAdsConfig_WebviewMode *_webviewModeDictionary;
    NSNumber<IMOptional> *_enablePubMuteControl;
}

@property(retain, nonatomic) NSNumber<IMOptional> *enablePubMuteControl; // @synthesize enablePubMuteControl=_enablePubMuteControl;
@property(retain, nonatomic) IMAdsConfig_WebviewMode *webviewModeDictionary; // @synthesize webviewModeDictionary=_webviewModeDictionary;
@property(retain, nonatomic) IMAdsConfigRendering_SaveContentModel *savecontent; // @synthesize savecontent=_savecontent;
@property(nonatomic) long long picQuality; // @synthesize picQuality=_picQuality;
@property(nonatomic) long long picHeight; // @synthesize picHeight=_picHeight;
@property(nonatomic) long long picWidth; // @synthesize picWidth=_picWidth;
@property(nonatomic) _Bool shouldRenderPopup; // @synthesize shouldRenderPopup=_shouldRenderPopup;
@property(nonatomic) long long renderTimeout; // @synthesize renderTimeout=_renderTimeout;
- (void).cxx_destruct;
- (_Bool)validate:(id *)arg1;
- (id)init;

@end

