//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

@class NSArray;

@interface IMAdsConfigRendering_SaveContentModel : IMJSONModel
{
    NSArray *_allowedContentType;
    long long _maxSaveSize;
}

@property(nonatomic) long long maxSaveSize; // @synthesize maxSaveSize=_maxSaveSize;
@property(retain, nonatomic) NSArray *allowedContentType; // @synthesize allowedContentType=_allowedContentType;
- (void).cxx_destruct;
- (_Bool)validate:(id *)arg1;
- (id)init;

@end

