//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

@class IMAdsConfigCacheModel;

@interface IMAdsConfig_Cache : IMJSONModel
{
    IMAdsConfigCacheModel *_base;
    IMAdsConfigCacheModel *_interstitial;
    IMAdsConfigCacheModel *_native;
}

+ (id)keyMapper;
@property(retain, nonatomic) IMAdsConfigCacheModel *native; // @synthesize native=_native;
@property(retain, nonatomic) IMAdsConfigCacheModel *interstitial; // @synthesize interstitial=_interstitial;
@property(retain, nonatomic) IMAdsConfigCacheModel *base; // @synthesize base=_base;
- (void).cxx_destruct;
- (_Bool)validate:(id *)arg1;
- (id)init;

@end

