//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMUIAction.h"
#import "IMVisibilityDelegate.h"

@class IMUIProperties, NSArray, NSDictionary, NSNumber, NSString, UIView;

@interface IMAsset : NSObject <IMUIAction, IMVisibilityDelegate>
{
    _Bool _shouldRecycle;
    _Bool _shouldFailAdOnAssetFailure;
    _Bool _shouldTrackVisibility;
    _Bool _isAnimating;
    _Bool _animationPaused;
    NSString *_name;
    NSDictionary *_style;
    NSArray *_value;
    NSString *_type;
    NSDictionary *_onClickParams;
    id <IMAssetBuilderDelegate> _delegate;
    UIView *_view;
    NSDictionary *_assetJson;
    NSString *_jPath;
    IMUIProperties *_properties;
    NSString *_styleRef;
    NSDictionary *_styles;
    NSString *_assetId;
    IMAsset *_assetRoot;
    unsigned long long _currentState;
    id <IMAssetActionDelegate> _actionDelegate;
    id <IMAssetTelemetryEventDelegate> _telemetryDelegate;
    unsigned long long _showTimeStamp;
    NSNumber *_enableScrolling;
    double _layerSpeed;
}

@property double layerSpeed; // @synthesize layerSpeed=_layerSpeed;
@property _Bool animationPaused; // @synthesize animationPaused=_animationPaused;
@property _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property _Bool shouldTrackVisibility; // @synthesize shouldTrackVisibility=_shouldTrackVisibility;
@property(retain, nonatomic) NSNumber *enableScrolling; // @synthesize enableScrolling=_enableScrolling;
@property _Bool shouldFailAdOnAssetFailure; // @synthesize shouldFailAdOnAssetFailure=_shouldFailAdOnAssetFailure;
@property _Bool shouldRecycle; // @synthesize shouldRecycle=_shouldRecycle;
@property(nonatomic) unsigned long long showTimeStamp; // @synthesize showTimeStamp=_showTimeStamp;
@property(nonatomic) __weak id <IMAssetTelemetryEventDelegate> telemetryDelegate; // @synthesize telemetryDelegate=_telemetryDelegate;
@property(nonatomic) __weak id <IMAssetActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(readonly, nonatomic) unsigned long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak IMAsset *assetRoot; // @synthesize assetRoot=_assetRoot;
@property(retain, nonatomic) NSString *assetId; // @synthesize assetId=_assetId;
@property(retain, nonatomic) NSDictionary *styles; // @synthesize styles=_styles;
@property(retain, nonatomic) NSString *styleRef; // @synthesize styleRef=_styleRef;
@property(retain, nonatomic) IMUIProperties *properties; // @synthesize properties=_properties;
@property(readonly, nonatomic) NSString *jPath; // @synthesize jPath=_jPath;
@property(readonly, nonatomic) NSDictionary *assetJson; // @synthesize assetJson=_assetJson;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak id <IMAssetBuilderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *onClickParams; // @synthesize onClickParams=_onClickParams;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSArray *value; // @synthesize value=_value;
@property(retain, nonatomic) NSDictionary *style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)foundSKStoreWithID:(id)arg1;
- (void)resumeAnimation;
- (void)pauseAnimation;
- (void)startAnimating;
- (_Bool)shouldAnimate;
- (double)assetDuration;
- (void)viewVisibilityComputedAs:(double)arg1;
- (void)screenDismissed;
- (void)screenPresented;
- (id)assetOnClickParams;
- (id)getTrackersOfType:(id)arg1;
- (id)getTrackersOfType:(id)arg1 withProperties:(id)arg2;
- (id)getAssetURLWithProperties:(id)arg1;
- (void)destroyed;
- (void)clicked;
- (void)rendered;
- (void)failed;
- (void)built;
- (void)building;
- (void)created;
- (void)view:(id)arg1 clicked:(id)arg2;
- (void)sendCallbackForAssetFailed;
- (void)sendCallbackForAssetBuilt;
- (void)updatePropertiesOnView;
- (id)createViewWithProperties:(id)arg1;
- (void)fetchAssetResources;
- (void)buildAsset;
- (_Bool)isStyleValid;
- (void)resetAssetAndRebuild:(_Bool)arg1;
- (id)buildAssetView;
- (struct CGSize)getSize;
- (void)recycleViewHelper;
- (void)recycleView;
- (id)getNonObstuctiveViewForVideoViewability;
- (id)buildAssetViewWithScale:(double)arg1;
- (id)getAssetViewWithScale:(double)arg1;
- (id)initWithJson:(id)arg1 withStyles:(id)arg2 atJPath:(id)arg3;
- (id)init;
- (void)generateProperties:(id)arg1 fromJson:(id)arg2;
- (id)propertiesFromJson:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

