//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMRequest.h"

@interface IMCrashReportingRequest : IMRequest
{
}

- (id)buildEventsPayload:(id)arg1 withIncludeIds:(id)arg2;
- (id)initWithEvents:(id)arg1 forUrl:(id)arg2 withIncludeIds:(id)arg3;

@end

