//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMIASViewability.h"

@class InMobi_AbstractAvidAdSession;

@interface IMIASWebViewability : IMIASViewability
{
    InMobi_AbstractAvidAdSession *_adSession;
}

@property(retain, nonatomic) InMobi_AbstractAvidAdSession *adSession; // @synthesize adSession=_adSession;
- (void).cxx_destruct;
- (void)dealloc;
- (void)startRecordingForDeferredViewability;
- (void)addFriendlyViews:(id)arg1;
- (void)attachViewabilityToView:(id)arg1;
- (void)createVideoAdSession;
- (void)createDisplayAdSession;
- (void)createAdSession;
- (id)initWithCreativeType:(long long)arg1 forDeferredTracking:(_Bool)arg2;

@end

