//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

@interface IMIceWIFIConfig : IMJSONModel
{
    _Bool _cwe;
}

@property(nonatomic) _Bool cwe; // @synthesize cwe=_cwe;
- (id)init;

@end

