//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAsset.h"

#import "IMAssetCacheDelegate.h"
#import "IMTimerDelegate.h"

@class IMTimerManager, IMVastCompanion, NSArray, NSData, NSString, UIImage;

@interface IMImageAsset : IMAsset <IMAssetCacheDelegate, IMTimerDelegate>
{
    _Bool _isViewHidden;
    _Bool _prevUserInteractionEnabled;
    _Bool _delayTimerHit;
    NSData *_imageData;
    UIImage *_image;
    NSString *_imageUrl;
    double _startImageFetchTS;
    long long _displayDelay;
    NSString *_displayReference;
    NSString *_displayReferenceType;
    long long _hideAfterDelay;
    IMTimerManager *_delayTimer;
    IMVastCompanion *_companion;
    NSArray *_companionErrorTrackers;
    unsigned long long _assetSubType;
    unsigned long long _imageLoadingType;
}

@property(nonatomic) unsigned long long imageLoadingType; // @synthesize imageLoadingType=_imageLoadingType;
@property(nonatomic) unsigned long long assetSubType; // @synthesize assetSubType=_assetSubType;
@property(retain, nonatomic) NSArray *companionErrorTrackers; // @synthesize companionErrorTrackers=_companionErrorTrackers;
@property(retain, nonatomic) IMVastCompanion *companion; // @synthesize companion=_companion;
@property(nonatomic) _Bool delayTimerHit; // @synthesize delayTimerHit=_delayTimerHit;
@property(nonatomic) _Bool prevUserInteractionEnabled; // @synthesize prevUserInteractionEnabled=_prevUserInteractionEnabled;
@property(retain, nonatomic) IMTimerManager *delayTimer; // @synthesize delayTimer=_delayTimer;
@property(nonatomic) long long hideAfterDelay; // @synthesize hideAfterDelay=_hideAfterDelay;
@property(retain, nonatomic) NSString *displayReferenceType; // @synthesize displayReferenceType=_displayReferenceType;
@property(retain, nonatomic) NSString *displayReference; // @synthesize displayReference=_displayReference;
@property(nonatomic) long long displayDelay; // @synthesize displayDelay=_displayDelay;
@property(nonatomic) double startImageFetchTS; // @synthesize startImageFetchTS=_startImageFetchTS;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(nonatomic) _Bool isViewHidden; // @synthesize isViewHidden=_isViewHidden;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
- (void).cxx_destruct;
- (void)updatePropertiesOnView;
- (id)createViewWithProperties:(id)arg1;
- (void)dealloc;
- (void)fireCompanionErrorTrackerForURL:(id)arg1;
- (void)checkAndFailPrefetchImageAssetLoading;
- (void)assetAddToCacheFailedForURL:(id)arg1 withError:(id)arg2;
- (void)assetReturningFromNetworkAt:(id)arg1 forURL:(id)arg2;
- (void)assetReturnedFromCacheAt:(id)arg1 forURL:(id)arg2;
- (void)populateImage:(id)arg1;
- (void)fireCompanionViewTrackers;
- (void)showView;
- (void)hideView;
- (void)timerHitForManager:(id)arg1;
- (void)videoQuartileHit;
- (id)urlByReplacingCacheBustingMacro:(id)arg1;
- (void)setFallbackCloseButtonImage;
- (void)createFallbackCloseButton;
- (void)addImageToViewWithTransition:(_Bool)arg1;
- (void)fetchAssetResources;
- (_Bool)isStyleValid;
- (void)recycleView;
- (id)buildAssetViewWithScale:(double)arg1;
- (id)initWithJson:(id)arg1 withStyles:(id)arg2 atJPath:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

