//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@class NSData, NSHTTPURLResponse;

@interface IMJSONModelError : NSError
{
    NSHTTPURLResponse *_httpResponse;
    NSData *_responseData;
}

+ (id)errorInputIsNil;
+ (id)errorModelIsInvalid;
+ (id)errorBadJSON;
+ (id)errorBadResponse;
+ (id)errorInvalidDataWithTypeMismatch:(id)arg1;
+ (id)errorInvalidDataWithMissingKeys:(id)arg1;
+ (id)errorInvalidDataWithMessage:(id)arg1;
@property(retain, nonatomic) NSData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSHTTPURLResponse *httpResponse; // @synthesize httpResponse=_httpResponse;
- (void).cxx_destruct;
- (id)errorByPrependingKeyPathComponent:(id)arg1;

@end

