//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMPlacementDao : NSObject
{
}

- (void)deleteAllPlacements;
- (void)cleanUpWithTimeToLive:(long long)arg1 expiredCount:(long long *)arg2;
- (void)updateTableForPlacementId:(long long)arg1 withAdType:(id)arg2 withTP:(id)arg3 maxLimit:(long long)arg4 overflow:(long long *)arg5;
- (id)getAllPlacements;
- (id)createTableSQL;
- (id)init;

@end

