//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMPublisherProvidedInfo : NSObject
{
}

+ (id)getLocationCountry;
+ (id)getLocationState;
+ (id)getLocationCity;
+ (void)setLocationWithCity:(id)arg1 state:(id)arg2 country:(id)arg3;
+ (id)getLocation;
+ (void)setLocation:(id)arg1;
+ (_Bool)isLocationValid:(double)arg1 longitude:(double)arg2;
+ (id)getAgeGroup;
+ (void)setAgeGroup:(long long)arg1;
+ (id)getInterests;
+ (void)setInterests:(id)arg1;
+ (id)getAreaCode;
+ (void)setAreaCode:(id)arg1;
+ (id)getPostalCode;
+ (void)setPostalCode:(id)arg1;
+ (id)getLanguage;
+ (void)setLanguage:(id)arg1;
+ (long long)getAge;
+ (void)setAge:(long long)arg1;
+ (long long)getYearOfBirth;
+ (void)setYearOfBirth:(long long)arg1;
+ (id)getEducation;
+ (void)setEducation:(long long)arg1;
+ (id)getGender;
+ (void)setGender:(long long)arg1;
+ (long long)getLogLevel;
+ (void)setLogLevel:(long long)arg1;
+ (id)publisherSiteId;
+ (id)convertToStringForAgeGroup:(long long)arg1;
+ (id)convertToStringForEducation:(long long)arg1;
+ (id)convertToStringForGender:(long long)arg1;

@end

