//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMSafariViewController;

@protocol IMSafariViewControllerDelegate <NSObject>
- (void)imSafariViewControllerDidDismissScreen:(IMSafariViewController *)arg1;
- (void)imSafariViewControllerWillDismissScreen:(IMSafariViewController *)arg1;
@end

