//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IMTRCEvent : NSObject
{
    NSString *_adType;
    NSString *_eventUUID;
    NSString *_eventName;
    NSString *_eventType;
    NSString *_placementId;
    NSString *_requestId;
    NSString *_markupType;
    double _timestamp;
    NSString *_netType;
}

+ (id)trcEventWithName:(id)arg1 includeIds:(id)arg2 placement:(long long)arg3 requestId:(id)arg4;
+ (id)trcEventWithName:(id)arg1 adType:(id)arg2 includeIds:(id)arg3 placement:(long long)arg4 requestId:(id)arg5 andMarkupType:(id)arg6;
+ (id)trcEventWithName:(id)arg1 eventType:(id)arg2 adType:(id)arg3 includeIds:(id)arg4 placement:(long long)arg5 requestId:(id)arg6 andMarkupType:(id)arg7;
@property(retain, nonatomic) NSString *netType; // @synthesize netType=_netType;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *markupType; // @synthesize markupType=_markupType;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(retain, nonatomic) NSString *eventType; // @synthesize eventType=_eventType;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(readonly, nonatomic) NSString *eventUUID; // @synthesize eventUUID=_eventUUID;
@property(retain, nonatomic) NSString *adType; // @synthesize adType=_adType;
- (void).cxx_destruct;
- (id)init;

@end

