//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "IMUIInflator.h"

@class IMUIProperties, NSString;

@interface IMUIButton : UIButton <IMUIInflator>
{
    IMUIProperties *_properties;
}

@property(retain, nonatomic) IMUIProperties *properties; // @synthesize properties=_properties;
- (void).cxx_destruct;
- (void)buttonClicked:(id)arg1;
- (void)clearProperties;
- (id)initWithProperties:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

