//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMUIProperties.h"

@class UICollectionViewFlowLayout;

@interface IMUICollectionViewProperties : IMUIProperties
{
    _Bool _shouldScrollToTop;
    UICollectionViewFlowLayout *_flowLayout;
}

@property(nonatomic) _Bool shouldScrollToTop; // @synthesize shouldScrollToTop=_shouldScrollToTop;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
- (void).cxx_destruct;

@end

