//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMVastMediaFile;

@interface IMVastBitRateMediaFileNode : NSObject
{
    long long _contentlength;
    IMVastMediaFile *_mediaFile;
}

@property(retain, nonatomic) IMVastMediaFile *mediaFile; // @synthesize mediaFile=_mediaFile;
@property(nonatomic) long long contentlength; // @synthesize contentlength=_contentlength;
- (void).cxx_destruct;
- (id)init;

@end

