//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, UIColor, UIFont, UIViewController;

@interface InfoFlowAPI : NSObject
{
    id <InfoFlowAPIDelegate> _delegate;
    UIFont *_titleFont;
    UIColor *_titleColor;
    NSString *_userId;
    NSString *_appId;
    NSString *_appKey;
    UIViewController *_viewController;
    NSMutableArray *_flowViewArray;
}

@property(retain, nonatomic) NSMutableArray *flowViewArray; // @synthesize flowViewArray=_flowViewArray;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(nonatomic) __weak id <InfoFlowAPIDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getNetWorkStates;
- (void)fetchInfoFlow:(id)arg1 type:(long long)arg2;
- (id)initWithUserId:(id)arg1 appId:(id)arg2 appKey:(id)arg3;

@end

