//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "INMMoatBridge.h"

#import "INMMoatBridgeProtocol.h"

@class NSString, UIWebView;

@interface INMMoatUIWebViewBridge : INMMoatBridge <INMMoatBridgeProtocol>
{
    UIWebView *_webView;
}

@property __weak UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)handleJSResponse:(id)arg1;
- (void)checkAndSendJS:(id)arg1;
- (id)initWithWebView:(id)arg1 forNativeAds:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

