//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface InMobi_AvidAdSessionManager : NSObject
{
}

+ (id)findWebView:(id)arg1;
+ (id)webViewForView:(id)arg1;
+ (id)webViewForSessionId:(id)arg1;
+ (id)startAvidManagedDisplayAdSessionWithContext:(id)arg1;
+ (id)startAvidManagedVideoAdSessionWithContext:(id)arg1;
+ (id)startAvidDisplayAdSessionWithContext:(id)arg1;
+ (id)startAvidVideoAdSessionWithContext:(id)arg1;
+ (id)releaseDate;
+ (id)version;

@end

