//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "InMobi_AvidVideoPlaybackListener.h"

@class InMobi_AvidEventDispatcher, InMobi_InternalAvidManagedVideoAdSession, NSString;

@interface InMobi_AvidVideoPlaybackListenerImpl : NSObject <InMobi_AvidVideoPlaybackListener>
{
    InMobi_AvidEventDispatcher *_dispatcher;
    InMobi_InternalAvidManagedVideoAdSession *_avidVideoAdSession;
}

@property(readonly, nonatomic) InMobi_InternalAvidManagedVideoAdSession *avidVideoAdSession; // @synthesize avidVideoAdSession=_avidVideoAdSession;
@property(nonatomic) __weak InMobi_AvidEventDispatcher *dispatcher; // @synthesize dispatcher=_dispatcher;
- (void).cxx_destruct;
- (void)publishVideoEvent:(id)arg1 data:(id)arg2;
- (void)recordAdErrorWithMessage:(id)arg1;
- (void)recordAdDurationChangeEvent:(id)arg1 adRemainingTime:(id)arg2;
- (void)recordAdExitedFullscreenEvent;
- (void)recordAdEnteredFullscreenEvent;
- (void)recordAdVolumeChangeEvent:(long long)arg1;
- (void)recordAdSkippedEvent;
- (void)recordAdUserCloseEvent;
- (void)recordAdUserAcceptInvitationEvent;
- (void)recordAdUserMinimizeEvent;
- (void)recordAdExpandedChangeEvent;
- (void)recordAdPlayingEvent;
- (void)recordAdPausedEvent;
- (void)recordAdVideoThirdQuartileEvent;
- (void)recordAdVideoMidpointEvent;
- (void)recordAdVideoFirstQuartileEvent;
- (void)recordAdClickThruEvent;
- (void)recordAdCompleteEvent;
- (void)recordAdStoppedEvent;
- (void)recordAdVideoStartEvent;
- (void)recordAdLoadedEvent;
- (void)recordAdStartedEvent;
- (void)recordAdImpressionEvent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

