//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface InMobi_ExternalAvidAdSessionContext : NSObject
{
    _Bool _isDeferred;
    NSString *_partnerVersion;
}

+ (id)contextWithPartnerVersion:(id)arg1 isDeferred:(_Bool)arg2;
+ (id)contextWithPartnerVersion:(id)arg1;
@property(readonly, nonatomic) _Bool isDeferred; // @synthesize isDeferred=_isDeferred;
@property(readonly, nonatomic) NSString *partnerVersion; // @synthesize partnerVersion=_partnerVersion;
- (void).cxx_destruct;
- (id)initWithPartnerVersion:(id)arg1 isDeferred:(_Bool)arg2;
- (id)initWithPartnerVersion:(id)arg1;

@end

