//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHReportRequest.h"

@class JCOREAPNSStateEntity, NSString;

@interface JCOREAPNSStateRequest : JPUSHReportRequest
{
    JCOREAPNSStateEntity *_state;
    unsigned long long _triggerScence;
    NSString *_deviceID;
}

@property(copy, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(nonatomic) unsigned long long triggerScence; // @synthesize triggerScence=_triggerScence;
@property(retain, nonatomic) JCOREAPNSStateEntity *state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)setResponseBlock;
- (_Bool)packData;
- (id)init;

@end

