//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface JCOREHttpAddressSis : NSObject
{
    _Bool _requesting;
}

@property(nonatomic) _Bool requesting; // @synthesize requesting=_requesting;
- (void)requst:(id)arg1 result:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool expired;
@property(nonatomic) double nextRequestTime;
@property(readonly, nonatomic) NSArray *normalReportAddressList;
- (void)setReportAddressDict:(id)arg1;
@property(readonly, nonatomic) NSDictionary *reportAddressDict;
- (void)setSisIpsFromServer:(id)arg1;
@property(readonly, nonatomic) NSArray *sisIpsFromServer;

@end

