//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class JPUSHReportRequest, NSError, NSString;

@protocol JPUSHHttpRequestDelegate
- (void)didNotReceivedFromRequest:(JPUSHReportRequest *)arg1 withReportFlag:(NSString *)arg2 WithError:(NSError *)arg3;
- (void)didReceivedHttpFeedback:(id)arg1;
@end

