//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface JPUSHLoggerNode : NSObject
{
    id <JPUSHLogger> _logger;
    unsigned long long _level;
    NSObject<OS_dispatch_queue> *_loggerQueue;
}

+ (id)nodeWithLogger:(id)arg1 loggerQueue:(id)arg2 level:(unsigned long long)arg3;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *loggerQueue; // @synthesize loggerQueue=_loggerQueue;
@property(readonly, nonatomic) unsigned long long level; // @synthesize level=_level;
@property(readonly, nonatomic) id <JPUSHLogger> logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithLogger:(id)arg1 loggerQueue:(id)arg2 level:(unsigned long long)arg3;

@end

