//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPUSHRequest.h"

@interface JPUSHIDFAReportRequest : JPUSHRequest
{
}

- (void)handleResponse:(id)arg1;
- (Class)responseClass;
- (_Bool)packData;
- (id)init;

@end

