//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class JPUSHPageFlow, NSString;

@interface JPUSHPageFlowSession : NSObject <NSCopying>
{
    _Bool _isSetup;
    JPUSHPageFlow *_currentFlow;
    NSString *_currentPageName;
}

@property(readonly, nonatomic) _Bool isSetup; // @synthesize isSetup=_isSetup;
@property(retain) NSString *currentPageName; // @synthesize currentPageName=_currentPageName;
@property(retain) JPUSHPageFlow *currentFlow; // @synthesize currentFlow=_currentFlow;
- (void).cxx_destruct;
- (void)p_movePageFromTempFlowToCurrentFlow:(id)arg1;
- (void)setViewLogSecond:(id)arg1;
- (void)setViewStop:(id)arg1;
- (void)setViewStart:(id)arg1;
- (id)findPageInFlow:(id)arg1 withName:(id)arg2;
- (void)p_saveCurrentFlow;
- (void)resetCurrentPage:(double)arg1;
- (void)savePageFlowWithTime:(double)arg1;
- (void)p_resumePagesFromFileWithTime:(double)arg1;
- (_Bool)resumeLastFlow;
- (void)closeSession;
- (void)setupSession;
- (void)trySetupSession;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

