//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMAlbumDetailModel, LZMImageView, UIImageView, UILabel;

@interface LZMAblumDetailCell : UICollectionViewCell
{
    LZMAlbumDetailModel *_dataModel;
    LZMImageView *_coverImageView;
    UIImageView *_backgroundImgView;
    UILabel *_scoreLabel;
    UILabel *_nameLabel;
    UIImageView *_trailerImage;
}

@property(retain, nonatomic) UIImageView *trailerImage; // @synthesize trailerImage=_trailerImage;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UIImageView *backgroundImgView; // @synthesize backgroundImgView=_backgroundImgView;
@property(retain, nonatomic) LZMImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) LZMAlbumDetailModel *dataModel; // @synthesize dataModel=_dataModel;
- (void).cxx_destruct;
- (void)makeConstraint;
- (id)initWithFrame:(struct CGRect)arg1;

@end

