//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol LZMAdBaseManagerDelegate <NSObject>

@optional
- (void)backAction;
- (void)shutDownCurrentAdType:(long long)arg1 palceId:(long long)arg2 andCurrentAd:(id)arg3;
- (void)reportError:(long long)arg1 adPalceId:(long long)arg2 aAdSupportType:(long long)arg3;
- (void)reportEvent:(NSString *)arg1 adPlaceType:(NSString *)arg2 andAdSupportName:(NSString *)arg3;
- (void)nativeAdObjectsSuccessLoad:(NSArray *)arg1 palceId:(long long)arg2 andAdSupportType:(long long)arg3;
- (void)prollADExitFullScreen:(_Bool)arg1;
@end

