//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMViewController.h"

#import "LZMActivityViewDelegate.h"
#import "LZMSegmentControlDelegate.h"

@class LZMActivityView, LZMSegmentControl, NSMutableArray, NSString;

@interface LZMClassifyTableController : LZMViewController <LZMSegmentControlDelegate, LZMActivityViewDelegate>
{
    long long _categoryId;
    long long _typeId;
    NSMutableArray *_segmentItemArray;
    NSMutableArray *_segmentNameArray;
    NSMutableArray *_videoTypeArray;
    NSMutableArray *_areaArray;
    NSMutableArray *_timeArray;
    NSMutableArray *_videoSortArray;
    NSMutableArray *_screenPlateArray;
    LZMSegmentControl *_segmentControl;
    LZMActivityView *_loadWaiting;
}

@property(retain, nonatomic) LZMActivityView *loadWaiting; // @synthesize loadWaiting=_loadWaiting;
@property(retain, nonatomic) LZMSegmentControl *segmentControl; // @synthesize segmentControl=_segmentControl;
@property(retain, nonatomic) NSMutableArray *screenPlateArray; // @synthesize screenPlateArray=_screenPlateArray;
@property(retain, nonatomic) NSMutableArray *videoSortArray; // @synthesize videoSortArray=_videoSortArray;
@property(retain, nonatomic) NSMutableArray *timeArray; // @synthesize timeArray=_timeArray;
@property(retain, nonatomic) NSMutableArray *areaArray; // @synthesize areaArray=_areaArray;
@property(retain, nonatomic) NSMutableArray *videoTypeArray; // @synthesize videoTypeArray=_videoTypeArray;
@property(retain, nonatomic) NSMutableArray *segmentNameArray; // @synthesize segmentNameArray=_segmentNameArray;
@property(retain, nonatomic) NSMutableArray *segmentItemArray; // @synthesize segmentItemArray=_segmentItemArray;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
@property(nonatomic) long long categoryId; // @synthesize categoryId=_categoryId;
- (void).cxx_destruct;
- (void)segmentControlDidselectAtIndex:(long long)arg1;
- (void)lzm_ActivityViewRefresh:(id)arg1;
- (void)searchButtonAction:(id)arg1;
- (void)buildNavbarButton;
- (void)initSubViews;
- (void)configDataWithModel:(id)arg1;
- (void)requestSegmentItemWithCategoryId:(long long)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

