//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface LZMChooseCustomTitleCell : UITableViewCell
{
    UILabel *_titleLB;
}

@property(retain, nonatomic) UILabel *titleLB; // @synthesize titleLB=_titleLB;
- (void).cxx_destruct;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

