//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSMutableArray, NSString;

@interface LZMDateModel : NSObject
{
    long long _weekIndex;
    NSString *_week;
    NSString *_currentDate;
    NSString *_dateMode;
    NSMutableArray *_programList;
    NSIndexPath *_indexPath;
}

@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) NSMutableArray *programList; // @synthesize programList=_programList;
@property(copy, nonatomic) NSString *dateMode; // @synthesize dateMode=_dateMode;
@property(copy, nonatomic) NSString *currentDate; // @synthesize currentDate=_currentDate;
@property(copy, nonatomic) NSString *week; // @synthesize week=_week;
@property(nonatomic) long long weekIndex; // @synthesize weekIndex=_weekIndex;
- (void).cxx_destruct;

@end

