//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMChooseDownloadItemModel;

@interface LZMDownloadNumberCell : UICollectionViewCell
{
    LZMChooseDownloadItemModel *_model;
}

@property(retain, nonatomic) LZMChooseDownloadItemModel *model; // @synthesize model=_model;
- (void).cxx_destruct;

@end

