//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView;

@interface LZMFailView : UIView
{
    id <LZMFailViewDelegate> _delegate;
    UIImageView *_placeHolderImageView;
    UIButton *_refreshButton;
}

@property(retain, nonatomic) UIButton *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) UIImageView *placeHolderImageView; // @synthesize placeHolderImageView=_placeHolderImageView;
@property(nonatomic) __weak id <LZMFailViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)refreshButtonAction:(id)arg1;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

