//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMImageView, LZMVideoModel, NSArray, UIImageView, YYLabel;

@interface LZMFVerticalViewCell : UICollectionViewCell
{
    _Bool _isGetUrl;
    LZMVideoModel *_videoDetailModel;
    LZMImageView *_coverImageView;
    YYLabel *_titleLabel;
    YYLabel *_viewCountLabel;
    UIImageView *_shadowImgView;
    NSArray *_lastInArray;
    UIImageView *_trailerImageView;
}

@property(retain, nonatomic) UIImageView *trailerImageView; // @synthesize trailerImageView=_trailerImageView;
@property(retain, nonatomic) NSArray *lastInArray; // @synthesize lastInArray=_lastInArray;
@property(retain, nonatomic) UIImageView *shadowImgView; // @synthesize shadowImgView=_shadowImgView;
@property(retain, nonatomic) YYLabel *viewCountLabel; // @synthesize viewCountLabel=_viewCountLabel;
@property(retain, nonatomic) YYLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) LZMImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(nonatomic) _Bool isGetUrl; // @synthesize isGetUrl=_isGetUrl;
@property(retain, nonatomic) LZMVideoModel *videoDetailModel; // @synthesize videoDetailModel=_videoDetailModel;
- (void).cxx_destruct;
- (void)LZMVerticalViewCellConfigModel:(id)arg1;
- (void)configRoomlistModel:(id)arg1;
- (void)makeConstraints;
- (void)setSubViewsForModel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

