//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString;

@interface LZMLiveNoticeChangeSourceView : UIView <UIGestureRecognizerDelegate>
{
}

- (void)setHidden:(_Bool)arg1;
- (void)singleTapAction:(id)arg1;
- (void)buildGestureRecognizer;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

