//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class LZMTvGroupModel, NSMutableArray, NSString, UITableView;

@interface LZMPlaceLivingViewController : LZMViewController <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate>
{
    LZMTvGroupModel *_model;
    UITableView *_provinceTableView;
    UITableView *_channelTableView;
    NSMutableArray *_dataArray;
    NSString *_url;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UITableView *channelTableView; // @synthesize channelTableView=_channelTableView;
@property(retain, nonatomic) UITableView *provinceTableView; // @synthesize provinceTableView=_provinceTableView;
@property(retain, nonatomic) LZMTvGroupModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)visibleChannelProgramListManage;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)buildUI;
- (void)requestProgramListDataChannelModel:(long long)arg1 withIndexPath:(id)arg2;
- (void)requsetChannelTablePlaceId:(long long)arg1;
- (void)requestPlaceTable;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

