//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface LZMQualityFileInfo : NSObject
{
    NSString *_quality;
    NSString *_fileUrl;
    NSDictionary *_requestHeader;
}

@property(retain, nonatomic) NSDictionary *requestHeader; // @synthesize requestHeader=_requestHeader;
@property(copy, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(nonatomic) NSString *quality; // @synthesize quality=_quality;
- (void).cxx_destruct;
- (id)formatQualityWithId:(long long)arg1;
- (id)description;

@end

