//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LZMShortVideoSourceModel : NSObject
{
    long long _videoSourceId;
    NSString *_playUrl;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *playUrl; // @synthesize playUrl=_playUrl;
@property(nonatomic) long long videoSourceId; // @synthesize videoSourceId=_videoSourceId;
- (void).cxx_destruct;

@end

