//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LZMToolModel : NSObject
{
}

+ (id)formatByteCount:(long long)arg1;
+ (long long)fileSizeAtPath:(id)arg1;
+ (long long)folderSizeAtPath:(id)arg1;
+ (long long)compareVersion:(id)arg1 to:(id)arg2;
+ (id)getClientNameAndVersion;
+ (id)getClientIdAndVersion;
+ (_Bool)isShieldWithChannelId:(long long)arg1;
+ (id)dateArray;
+ (long long)weekdayIndexFromDate:(id)arg1;
+ (id)createdMD5:(id)arg1;

@end

