//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LZMUserModel;

@interface LZMUserDataManager : NSObject
{
    LZMUserModel *_userModel;
}

+ (id)sharedInstance;
@property(retain, nonatomic) LZMUserModel *userModel; // @synthesize userModel=_userModel;
- (void).cxx_destruct;
- (void)synchronizationShortVideoData:(id)arg1 updateType:(long long)arg2;
- (void)synchronizationUserCustomChannelData:(id)arg1 updateType:(long long)arg2;
- (void)synchronizationProgramData:(id)arg1 updateType:(long long)arg2;
- (void)synchronizationLiveChannelData:(id)arg1 updateType:(long long)arg2;
- (void)synchronizationLongVideoData:(id)arg1 updateType:(long long)arg2;
- (void)changeLoginState:(_Bool)arg1;

@end

