//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LZMVideoTypeModel : NSObject
{
    NSString *_name;
    long long _typeId;
    double _nameWidth;
}

+ (id)modelCustomPropertyMapper;
@property(nonatomic) double nameWidth; // @synthesize nameWidth=_nameWidth;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

