//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MOBFBigInteger;

@interface MOBFRSAKey : NSObject
{
    int _bits;
    MOBFBigInteger *_n;
    MOBFBigInteger *_e;
    MOBFBigInteger *_d;
}

@property(retain, nonatomic) MOBFBigInteger *d; // @synthesize d=_d;
@property(retain, nonatomic) MOBFBigInteger *e; // @synthesize e=_e;
@property(retain, nonatomic) MOBFBigInteger *n; // @synthesize n=_n;
@property(nonatomic) int bits; // @synthesize bits=_bits;
- (void).cxx_destruct;

@end

