//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface MOBFErrorReportConfi : NSObject <NSCoding>
{
    _Bool _uploadDataEnabled;
    NSString *_sdkType;
    NSString *_sdkVersion;
    NSString *_appKey;
    NSString *_requestURL;
    long long _crashLevel;
    long long _sdkErrLevel;
}

@property(nonatomic) long long sdkErrLevel; // @synthesize sdkErrLevel=_sdkErrLevel;
@property(nonatomic) long long crashLevel; // @synthesize crashLevel=_crashLevel;
@property(copy, nonatomic) NSString *requestURL; // @synthesize requestURL=_requestURL;
@property(nonatomic) _Bool uploadDataEnabled; // @synthesize uploadDataEnabled=_uploadDataEnabled;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(copy, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(copy, nonatomic) NSString *sdkType; // @synthesize sdkType=_sdkType;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithSDKType:(id)arg1 sdkVersion:(id)arg2 appKey:(id)arg3;

@end

