//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTVideoParserManager : NSObject
{
    id _parserDic;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id parserDic; // @synthesize parserDic=_parserDic;
- (void).cxx_destruct;
- (id)load:(id)arg1 andAnalysisUrl:(id)arg2;
- (id)load:(id)arg1 andSourceId:(int)arg2;
- (id)format:(id)arg1;
- (void)startUpSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (_Bool)isRegistered;

@end

