//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (WBSDKJSONKitSerializing)
- (id)weibosdk_WBSDKJSONStringWithOptions:(unsigned long long)arg1 serializeUnsupportedClassesUsingDelegate:(id)arg2 selector:(SEL)arg3 error:(id *)arg4;
- (id)weibosdk_WBSDKJSONStringWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)weibosdk_WBSDKJSONString;
- (id)weibosdk_WBSDKJSONDataWithOptions:(unsigned long long)arg1 serializeUnsupportedClassesUsingDelegate:(id)arg2 selector:(SEL)arg3 error:(id *)arg4;
- (id)weibosdk_WBSDKJSONDataWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)weibosdk_WBSDKJSONData;
@end

