//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (MJKeyValueDeprecated_v_2_5_16)
+ (id)objectArrayWithFile:(id)arg1 error:(id *)arg2;
+ (id)objectArrayWithFile:(id)arg1;
+ (id)objectArrayWithFilename:(id)arg1 error:(id *)arg2;
+ (id)objectArrayWithFilename:(id)arg1;
+ (id)objectArrayWithKeyValuesArray:(id)arg1 context:(id)arg2 error:(id *)arg3;
+ (id)objectArrayWithKeyValuesArray:(id)arg1 context:(id)arg2;
+ (id)objectArrayWithKeyValuesArray:(id)arg1 error:(id *)arg2;
+ (id)objectArrayWithKeyValuesArray:(id)arg1;
+ (id)objectWithFile:(id)arg1 error:(id *)arg2;
+ (id)objectWithFile:(id)arg1;
+ (id)objectWithFilename:(id)arg1 error:(id *)arg2;
+ (id)objectWithFilename:(id)arg1;
+ (id)objectWithKeyValues:(id)arg1 context:(id)arg2 error:(id *)arg3;
+ (id)objectWithKeyValues:(id)arg1 context:(id)arg2;
+ (id)objectWithKeyValues:(id)arg1 error:(id *)arg2;
+ (id)objectWithKeyValues:(id)arg1;
+ (id)keyValuesArrayWithObjectArray:(id)arg1 ignoredKeys:(id)arg2 error:(id *)arg3;
+ (id)keyValuesArrayWithObjectArray:(id)arg1 ignoredKeys:(id)arg2;
+ (id)keyValuesArrayWithObjectArray:(id)arg1 keys:(id)arg2 error:(id *)arg3;
+ (id)keyValuesArrayWithObjectArray:(id)arg1 keys:(id)arg2;
+ (id)keyValuesArrayWithObjectArray:(id)arg1 error:(id *)arg2;
+ (id)keyValuesArrayWithObjectArray:(id)arg1;
+ (void)referenceReplacedKeyWhenCreatingKeyValues:(_Bool)arg1;
- (id)JSONString;
- (id)JSONObject;
- (id)JSONData;
- (id)keyValuesWithIgnoredKeys:(id)arg1 error:(id *)arg2;
- (id)keyValuesWithIgnoredKeys:(id)arg1;
- (id)keyValuesWithKeys:(id)arg1 error:(id *)arg2;
- (id)keyValuesWithKeys:(id)arg1;
- (id)keyValuesWithError:(id *)arg1;
- (id)keyValues;
- (id)setKeyValues:(id)arg1 context:(id)arg2 error:(id *)arg3;
- (id)setKeyValues:(id)arg1 context:(id)arg2;
- (id)setKeyValues:(id)arg1 error:(id *)arg2;
- (id)setKeyValues:(id)arg1;
@end

