//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TDAACompress : NSObject
{
}

+ (id)uncompressGZippedData:(id)arg1;
+ (id)dataByGZipCompressing:(id)arg1;
+ (id)dataByZlibCompressing:(id)arg1;
+ (id)unCompressingData:(id)arg1 withCompressType:(long long)arg2;
+ (id)dataCompressingData:(id)arg1 withCompressType:(long long)arg2;

@end

