//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVEBaseModel.h"

@class NSString, TVEAd;

@interface TVEAdConfigs : TVEBaseModel
{
    NSString *_page;
    NSString *_type;
    TVEAd *_ad;
}

+ (id)tve_objectClassInArray;
@property(retain, nonatomic) TVEAd *ad; // @synthesize ad=_ad;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *page; // @synthesize page=_page;
- (void).cxx_destruct;

@end

