//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVEBase64 : NSObject
{
}

+ (int)char2Int:(BOOL)arg1;
+ (id)decode:(id)arg1;
+ (id)encode:(id)arg1;

@end

