//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TVESDCycleScrollViewDelegate.h"

@class NSMutableArray, NSString, TVESDCycleScrollView, TVESection;

@interface TVEFocusView : UIView <TVESDCycleScrollViewDelegate>
{
    id <TVEFocusViewDelegate> _delegate;
    TVESDCycleScrollView *_cycleScrollView;
    NSMutableArray *_titleArray;
    NSMutableArray *_imageArray;
    TVESection *_focusSection;
}

@property(retain, nonatomic) TVESection *focusSection; // @synthesize focusSection=_focusSection;
@property(retain, nonatomic) NSMutableArray *imageArray; // @synthesize imageArray=_imageArray;
@property(retain, nonatomic) NSMutableArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) TVESDCycleScrollView *cycleScrollView; // @synthesize cycleScrollView=_cycleScrollView;
@property(nonatomic) __weak id <TVEFocusViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setupCustomCell:(id)arg1 forIndex:(long long)arg2 cycleScrollView:(id)arg3;
- (Class)customCollectionViewCellClassForCycleScrollView:(id)arg1;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)loadData:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

