//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GDTNativeAdData, NSTimer, UIImageView, UILabel;

@interface TVEGDTNativeAdView : UIView
{
    int _timePlus;
    GDTNativeAdData *_nativeAdData;
    id <TVEGDTNativeAdViewDelegate> _delegate;
    UIImageView *_imageView;
    UILabel *_timeLabel;
    UILabel *_tipLabel;
    UIImageView *_logoImageView;
    NSTimer *_timer;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) int timePlus; // @synthesize timePlus=_timePlus;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak id <TVEGDTNativeAdViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GDTNativeAdData *nativeAdData; // @synthesize nativeAdData=_nativeAdData;
- (void).cxx_destruct;
- (void)dealloc;
- (void)removeFromSuperview;
- (void)timeFireDate;
- (void)refreshMediaControlControl;
- (void)viewTapped:(id)arg1;
- (void)setupMainView;
- (id)init;

@end

