//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TVEMXParallaxHeader;

@interface TVEMXParallaxView : UIView
{
    TVEMXParallaxHeader *_parent;
}

@property(nonatomic) __weak TVEMXParallaxHeader *parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (void)didMoveToSuperview;
- (void)willMoveToSuperview:(id)arg1;

@end

