//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol TVEMediaPlayerProtocol <NSObject>
@property(nonatomic) _Bool shouldAutoplay;
@property(readonly, nonatomic) struct CGSize naturalSize;
@property(readonly, nonatomic) _Bool isPlaying;
@property(readonly, nonatomic) unsigned long long loadState;
@property(readonly, nonatomic) long long playbackState;
@property(readonly, nonatomic) _Bool isPreparedToPlay;
@property(readonly, nonatomic) long long bufferingProgress;
@property(readonly, nonatomic) double playableDuration;
@property(readonly, nonatomic) double duration;
@property(nonatomic) double currentPlaybackTime;
@property(readonly, nonatomic) UIView *view;
@property(nonatomic) __weak id <TVEMediaPlayerDelegate> delegate;
@property(copy, nonatomic) NSString *contentURL;
@property(nonatomic) __weak UIView *fatherView;
- (void)setPauseInBackground:(_Bool)arg1;
- (void)shutdown;
- (void)stop;
- (void)pause;
- (void)play;
- (void)prepareToPlay;
@end

