//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVEMXPagerViewDataSource.h"

@class NSString, TVEMXPagerView, UIViewController;

@protocol TVEMXPagerViewControllerDataSource <TVEMXPagerViewDataSource>
- (NSString *)pagerView:(TVEMXPagerView *)arg1 segueIdentifierForPageAtIndex:(long long)arg2;
- (UIViewController *)pagerView:(TVEMXPagerView *)arg1 viewControllerForPageAtIndex:(long long)arg2;
@end

