//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@protocol TVEMediaPlayerDelegate <NSObject>

@optional
- (void)tveMediaPlayer:(id <TVEMediaPlayerProtocol>)arg1 updateConstraintsWithFatherView:(UIView *)arg2;
- (void)tveMediaPlayer:(id <TVEMediaPlayerProtocol>)arg1 playbackDidFinish:(long long)arg2;
- (void)tveMediaPlayer:(id <TVEMediaPlayerProtocol>)arg1 loadStateChanged:(unsigned long long)arg2;
- (void)tveMediaPlayer:(id <TVEMediaPlayerProtocol>)arg1 playbackStateChanged:(long long)arg2;
@end

