//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@interface UIControl (YYAdd)
- (id)_yy_allUIControlBlockTargets;
- (void)removeAllBlocksForControlEvents:(unsigned long long)arg1;
- (void)setBlockForControlEvents:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)addBlockForControlEvents:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)setTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned long long)arg3;
- (void)removeAllTargets;
@end

