//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

#import "NSCoding.h"

@interface UIFont (YYAdd) <NSCoding>
+ (id)dataFromCGFont:(struct CGFont *)arg1;
+ (id)dataFromFont:(id)arg1;
+ (_Bool)unloadFontFromData:(id)arg1;
+ (id)loadFontFromData:(id)arg1;
+ (void)unloadFontFromPath:(id)arg1;
+ (_Bool)loadFontFromPath:(id)arg1;
+ (id)fontWithCGFont:(struct CGFont *)arg1 size:(double)arg2;
+ (id)fontWithCTFont:(struct __CTFont *)arg1;
- (struct CGFont *)CGFontRef;
- (const struct __CTFont *)CTFontRef;
- (id)fontWithNormal;
- (id)fontWithBoldItalic;
- (id)fontWithItalic;
- (id)fontWithBold;
@property(readonly, nonatomic) double fontWeight;
@property(readonly, nonatomic) _Bool isColorGlyphs;
@property(readonly, nonatomic) _Bool isMonoSpace;
@property(readonly, nonatomic) _Bool isItalic;
@property(readonly, nonatomic) _Bool isBold;
@end

