//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (HighlightedWebCache)
- (void)gdtsd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;
- (void)gdtsd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 completed:(CDUnknownBlockType)arg3;
- (void)gdtsd_setHighlightedImageWithURL:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)gdtsd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2;
- (void)gdtsd_setHighlightedImageWithURL:(id)arg1;
@end

