//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (YYImageCoder)
- (id)_imageDataRepresentationForSystem:(_Bool)arg1;
- (id)imageDataRepresentation;
- (void)saveToAlbumWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool isDecodedForDisplay;
- (id)imageByDecoded;
@end

