//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (TVESDExtension)
@property(nonatomic) double tvesd_x;
@property(nonatomic) double tvesd_y;
@property(nonatomic) double tvesd_width;
@property(nonatomic) double tvesd_height;
@end

