//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialHandler.h"

#import "BriefWebControllerDelegate.h"
#import "UIWebViewDelegate.h"
#import "UMSocialPlatformProvider.h"

@class NSArray, NSString, UINavigationController;

@interface UMSocialSinaHandler : UMSocialHandler <UMSocialPlatformProvider, UIWebViewDelegate, BriefWebControllerDelegate>
{
    NSString *_wbtoken;
    NSString *_wbRefreshToken;
    NSString *_wbCurrentUserID;
    NSArray *_platformSchemeList;
    NSString *_currentInstalledScheme;
    UINavigationController *_sinaRootVC;
    NSString *_sinaKey;
    long long _sinaAction;
}

+ (id)socialPlatformTypes;
+ (id)defaultManager;
+ (void)load;
@property(nonatomic) long long sinaAction; // @synthesize sinaAction=_sinaAction;
@property(retain, nonatomic) NSString *sinaKey; // @synthesize sinaKey=_sinaKey;
@property(nonatomic) __weak UINavigationController *sinaRootVC; // @synthesize sinaRootVC=_sinaRootVC;
@property(retain, nonatomic) NSString *currentInstalledScheme; // @synthesize currentInstalledScheme=_currentInstalledScheme;
@property(retain, nonatomic) NSArray *platformSchemeList; // @synthesize platformSchemeList=_platformSchemeList;
@property(retain, nonatomic) NSString *wbCurrentUserID; // @synthesize wbCurrentUserID=_wbCurrentUserID;
@property(retain, nonatomic) NSString *wbRefreshToken; // @synthesize wbRefreshToken=_wbRefreshToken;
@property(retain, nonatomic) NSString *wbtoken; // @synthesize wbtoken=_wbtoken;
- (void).cxx_destruct;
- (id)encode:(id)arg1;
- (id)packageDictionaryWithDict:(id)arg1;
- (id)urlDecode:(id)arg1;
- (id)urlEncode:(id)arg1;
- (id)md5Value:(id)arg1;
- (id)joinComponentToString:(id)arg1;
- (void)sendAsyncRequestWithRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)sendAsyncRequestWithUrl:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)backFromBriefWebController;
- (void)briefWebView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)briefWebView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (id)parseResultUrl:(id)arg1;
- (void)handleShareResponse:(id)arg1 withSocialResponse:(id)arg2;
- (void)receiveShareResponse:(id)arg1 userInfo:(id)arg2;
- (void)sendRequestWithMessage:(id)arg1 userInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendShareRequest:(id)arg1 withType:(unsigned long long)arg2 andUserInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (unsigned long long)directShare:(id)arg1 withType:(unsigned long long)arg2 andUserInfo:(id)arg3;
- (void)handlerUserInfo:(id)arg1 withToken:(id)arg2 error:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)sendUserInfoRequest:(id)arg1 accesstoken:(id)arg2 CompletionHandler:(CDUnknownBlockType)arg3;
- (int)authWithScope:(id)arg1 userInfo:(id)arg2 URI:(id)arg3;
- (void)logoutSinaWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)loadAuthView:(id)arg1 userInfo:(id)arg2 URI:(id)arg3;
- (void)handleAuthResponse:(id)arg1 withSocialResponse:(id)arg2;
- (void)receiveAuthResponse:(id)arg1 userInfo:(id)arg2;
- (void)sendAuthRequest:(id)arg1 userInfo:(id)arg2 URI:(id)arg3;
- (id)sinaEncodeData:(id)arg1;
- (struct __SecKey *)getSinaKeyRefrenceFromeData:(id)arg1;
- (id)getSinaInfo;
- (void)requestSinaWeibo:(id)arg1 uri:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)checkSinaKey:(CDUnknownBlockType)arg1;
- (_Bool)handleOpenURL:(id)arg1;
- (unsigned long long)sendRequestWithObject:(id)arg1 userInfo:(id)arg2 andId:(id)arg3;
- (id)truncationTextForSina:(id)arg1 withTextLimit:(unsigned long long)arg2;
- (_Bool)checkSourceWordLength:(float)arg1 stepWordLength:(float)arg2 targetWordLength:(float)arg3;
- (void)shareToSinaWithMessage:(id)arg1 withType:(unsigned long long)arg2;
- (void)shareWebPage:(id)arg1;
- (void)shareVedio:(id)arg1;
- (void)shareMusic:(id)arg1;
- (void)shareImage:(id)arg1;
- (void)shareTextObject:(id)arg1;
- (void)umSocial_ShareWithObject:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)sendCancelAuth:(id)arg1;
- (void)umSocial_cancelAuthWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)umSocial_RequestForUserProfileWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)umSocial_AuthorizeWithUserInfo:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (_Bool)umSocial_handleOpenURL:(id)arg1;
- (void)umSocial_clearCacheData;
- (void)umSocial_setAppKey:(id)arg1 withAppSecret:(id)arg2 withRedirectURL:(id)arg3;
- (id)checkInstall;
- (_Bool)checkUrlSchema;
- (_Bool)umSocial_isSupport;
- (_Bool)umSocial_isInstall;
- (id)umSocial_PlatformSDKVersion;
- (unsigned long long)umSocial_SupportedFeatures;
- (void)configHandle;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long socialPlatformType;
@property(readonly) Class superclass;

@end

