//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface UMSocialNavigationInfo : NSObject
{
    NSString *_navTitle;
    NSString *_navBackTitle;
    UIColor *_navBackColor;
}

@property(retain, nonatomic) UIColor *navBackColor; // @synthesize navBackColor=_navBackColor;
@property(retain, nonatomic) NSString *navBackTitle; // @synthesize navBackTitle=_navBackTitle;
@property(retain, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
- (void).cxx_destruct;

@end

