//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMUtils : NSObject
{
}

+ (void)invoke:(id)arg1 selString:(id)arg2 enabled:(_Bool)arg3 md5:(id)arg4 returnValue:(void *)arg5;
+ (void)invoke:(id)arg1 selString:(id)arg2 enabled:(_Bool)arg3 returnValue:(void *)arg4;
+ (void)invoke:(id)arg1 selString:(id)arg2 object1:(id)arg3 selector:(SEL)arg4 returnValue:(void *)arg5;
+ (void)invoke:(id)arg1 selString:(id)arg2 object1:(id)arg3 object2:(id)arg4 returnValue:(void *)arg5;
+ (id)componentFlags;
+ (void)appendComponentFlag:(id)arg1;
+ (void)invoke:(id)arg1 selString:(id)arg2 argument:(id)arg3 returnValue:(void *)arg4;
+ (id)reflectObject:(id)arg1 selector:(id)arg2 object:(id)arg3 object:(id)arg4;
+ (id)reflectObject:(id)arg1 selector:(id)arg2 object:(id)arg3;
+ (id)reflectObject:(id)arg1 selector:(id)arg2;
+ (_Bool)loadSysFramework:(id)arg1;
+ (void)reflectClass:(id)arg1 selector:(id)arg2 params:(void **)arg3 paramsCount:(int)arg4;
+ (void)performClass:(id)arg1 method:(id)arg2 object:(id)arg3;
+ (id)deflatedDataPrefixedWith:(id)arg1 level:(int)arg2 source:(id)arg3;
+ (id)deflatedData:(id)arg1;
+ (_Bool)isEmptyString:(id)arg1;
+ (_Bool)notEmptyString:(id)arg1;
+ (id)getString:(id)arg1 bytesLength:(int)arg2;
+ (id)bytesToHexString:(char *)arg1 length:(int)arg2;
+ (id)AES128DecryptData:(id)arg1 withKey:(const void *)arg2;
+ (id)AES128EncryptData:(id)arg1 withKey:(const void *)arg2;
+ (id)decodeBase64:(id)arg1;
+ (id)encodeBase64:(id)arg1;
+ (id)JSONValue:(id)arg1;
+ (id)JSONFragment:(id)arg1;
+ (id)urlDecode:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (id)md5DataWithData:(id)arg1;
+ (char *)md5BytesWithString:(id)arg1;
+ (id)md5:(id)arg1;
+ (_Bool)isAppPirate;
+ (id)appPirateString;
+ (id)appShortVersionString;
+ (id)appBundleVersionString;
+ (id)realAppDisplayNameString;
+ (id)appDisplayNameString;
+ (id)appPackageNameString;
+ (id)mccString;
+ (id)mncString;
+ (id)carrierString;
+ (id)accessSubType;
+ (id)CTTelephonyNetworkInfoObject;
+ (int)accessStatus;
+ (id)accessString;
+ (id)batteryInfo;
+ (_Bool)isPad;
+ (id)deviceJailBreakString;
+ (_Bool)isDeviceJailBreak;
+ (id)resolutionString;
+ (id)deviceModelString;
+ (id)deviceMacAddressString;
+ (id)idfv;
+ (id)idfa;
+ (id)openUDIDString;
+ (id)utdid;
+ (id)deviceToken;
+ (id)dateString;
+ (id)timezoneString;
+ (int)timezone;
+ (id)languageString;
+ (id)countryString;
+ (id)osVersionString;
+ (id)osString;
+ (_Bool)isDebugging;
+ (unsigned long long)UTCIntervalMS;
+ (double)durationNowWith1970TimeInterval:(double)arg1;
+ (id)appkey;

@end

