//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UrlManager : NSObject
{
    NSString *_randkey;
    NSString *_fetchSpotUrl;
    NSString *_fetchBannerUrl;
    NSString *_fetchSplashUrl;
    NSString *_fetchInfoFlowUrl;
    NSString *_statisticsUrl;
}

+ (id)shareManager;
@property(readonly, copy, nonatomic) NSString *statisticsUrl; // @synthesize statisticsUrl=_statisticsUrl;
@property(readonly, copy, nonatomic) NSString *fetchInfoFlowUrl; // @synthesize fetchInfoFlowUrl=_fetchInfoFlowUrl;
@property(readonly, copy, nonatomic) NSString *fetchSplashUrl; // @synthesize fetchSplashUrl=_fetchSplashUrl;
@property(readonly, copy, nonatomic) NSString *fetchBannerUrl; // @synthesize fetchBannerUrl=_fetchBannerUrl;
@property(readonly, copy, nonatomic) NSString *fetchSpotUrl; // @synthesize fetchSpotUrl=_fetchSpotUrl;
@property(readonly, copy, nonatomic) NSString *randkey; // @synthesize randkey=_randkey;
- (void).cxx_destruct;
- (void)saveWholeUrlWithUrlDic:(id)arg1;

@end

