//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UTDDeviceInfo, UTDSDKInfo, UTDSession;

@interface UTDContext : NSObject
{
    UTDSDKInfo *_sdkInfo;
    UTDDeviceInfo *_deviceInfo;
    UTDSession *_currentSession;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedUTDContext;
@property(retain, nonatomic) UTDSession *currentSession; // @synthesize currentSession=_currentSession;
@property(retain, nonatomic) UTDDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
@property(retain, nonatomic) UTDSDKInfo *sdkInfo; // @synthesize sdkInfo=_sdkInfo;
- (void).cxx_destruct;
- (_Bool)valid;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

