//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UTDCacheManager, UTDLogUploadManager;

@interface UTDEngine : NSObject
{
    UTDLogUploadManager *_uploadManager;
    UTDCacheManager *_cacheManager;
    struct dispatch_queue_s *_storeQueue;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedUTDEngine;
- (void).cxx_destruct;
- (void)synchronize;
- (_Bool)addUTDLog:(id)arg1;
- (void)addLog:(id)arg1;
- (void)asyncAddLog:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

