//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WBDataTransferObject.h"

@class NSString;

@interface WBBaseRequest : WBDataTransferObject
{
    NSString *requestID;
    id <WeiboSDKRequestDelegate> delegate;
}

+ (Class)associateResponseClass;
+ (id)mappedObjectWithDictionary:(id)arg1;
+ (id)request;
+ (id)transferType;
+ (void)nothing;
@property(nonatomic) __weak id <WeiboSDKRequestDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *requestID; // @synthesize requestID;
- (void).cxx_destruct;
- (_Bool)canHandleByWeiboClientApp;
- (_Bool)canAssociateWithResponse:(id)arg1;
- (void)loadFromDictionary:(id)arg1;
- (void)storeToDictionary:(id)arg1;
- (id)objectID;
- (void)setObjectID:(id)arg1;
- (void)dealloc;

@end

