//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableData, NSString, NSURLConnection;

@interface WBHttpRequest : NSObject
{
    NSURLConnection *connection;
    NSMutableData *responseData;
    NSString *url;
    NSString *httpMethod;
    NSDictionary *params;
    id <WBHttpRequestDelegate> delegate;
    NSString *tag;
}

+ (void)cleanSubCookies;
+ (id)serializeURL:(id)arg1 params:(id)arg2 httpMethod:(id)arg3;
+ (id)requestWithAccessToken:(id)arg1 url:(id)arg2 httpMethod:(id)arg3 params:(id)arg4 queue:(id)arg5 withCompletionHandler:(CDUnknownBlockType)arg6 isGuest:(_Bool)arg7;
+ (id)requestWithAccessToken:(id)arg1 url:(id)arg2 httpMethod:(id)arg3 params:(id)arg4 delegate:(id)arg5 withTag:(id)arg6 isGuest:(_Bool)arg7;
+ (id)requestWithAccessToken:(id)arg1 url:(id)arg2 httpMethod:(id)arg3 params:(id)arg4 queue:(id)arg5 withCompletionHandler:(CDUnknownBlockType)arg6;
+ (id)requestWithAccessToken:(id)arg1 url:(id)arg2 httpMethod:(id)arg3 params:(id)arg4 delegate:(id)arg5 withTag:(id)arg6;
+ (id)requestWithURL:(id)arg1 httpMethod:(id)arg2 params:(id)arg3 queue:(id)arg4 withCompletionHandler:(CDUnknownBlockType)arg5;
+ (id)requestWithURL:(id)arg1 httpMethod:(id)arg2 params:(id)arg3 delegate:(id)arg4 withTag:(id)arg5;
@property(retain, nonatomic) NSString *tag; // @synthesize tag;
@property(nonatomic) __weak id <WBHttpRequestDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params;
@property(retain, nonatomic) NSString *httpMethod; // @synthesize httpMethod;
@property(retain, nonatomic) NSString *url; // @synthesize url;
- (void).cxx_destruct;
- (void)handleResponseData:(id)arg1;
- (void)failedWithError:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)appendUTF8Body:(id)arg1 dataString:(id)arg2;
- (id)postBodyHasRawData:(_Bool *)arg1;
- (void)disconnect;
- (void)setHttpHeaderForRequest:(id)arg1;
- (void)connectOnQueue:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)connect;
- (id)initWithURL:(id)arg1 httpMethod:(id)arg2 params:(id)arg3 queue:(id)arg4 withCompletionHandler:(CDUnknownBlockType)arg5;
- (id)initWithURL:(id)arg1 httpMethod:(id)arg2 params:(id)arg3 delegate:(id)arg4 withTag:(id)arg5;
- (void)dealloc;

@end

