//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXOMTABaseFunction : NSObject
{
}

+ (id)fetchSSIDInfo;
+ (id)getMTAStorePath;
+ (id)md5encrypt:(id)arg1;
+ (void)logDebug:(id)arg1;
+ (id)objToJson:(id)arg1;

@end

