//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextPosition.h"

#import "NSCopying.h"

@interface YYTextPosition : UITextPosition <NSCopying>
{
    long long _offset;
    long long _affinity;
}

+ (id)positionWithOffset:(long long)arg1 affinity:(long long)arg2;
+ (id)positionWithOffset:(long long)arg1;
@property(readonly, nonatomic) long long affinity; // @synthesize affinity=_affinity;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;
- (long long)compare:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

