//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ZM_GetTransportInfoModel : NSObject
{
    NSString *_currentTransportState;
    NSString *_currentTransportStatus;
    NSString *_currentSpeed;
}

@property(copy, nonatomic) NSString *currentSpeed; // @synthesize currentSpeed=_currentSpeed;
@property(copy, nonatomic) NSString *currentTransportStatus; // @synthesize currentTransportStatus=_currentTransportStatus;
@property(copy, nonatomic) NSString *currentTransportState; // @synthesize currentTransportState=_currentTransportState;
- (void).cxx_destruct;
- (void)setArray:(id)arg1;

@end

