//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, ZM_ServiceModel;

@interface ZM_UpnpModel : NSObject
{
    NSString *_friendlyName;
    NSString *_modelName;
    NSString *_deviceType;
    NSString *_urlHeader;
    ZM_ServiceModel *_AVTransportServiceModel;
    ZM_ServiceModel *_RenderControlServiceModel;
}

@property(retain, nonatomic) ZM_ServiceModel *RenderControlServiceModel; // @synthesize RenderControlServiceModel=_RenderControlServiceModel;
@property(retain, nonatomic) ZM_ServiceModel *AVTransportServiceModel; // @synthesize AVTransportServiceModel=_AVTransportServiceModel;
@property(copy, nonatomic) NSString *urlHeader; // @synthesize urlHeader=_urlHeader;
@property(copy, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(copy, nonatomic) NSString *modelName; // @synthesize modelName=_modelName;
@property(copy, nonatomic) NSString *friendlyName; // @synthesize friendlyName=_friendlyName;
- (void).cxx_destruct;
- (void)setArray:(id)arg1;
- (id)init;

@end

