//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AlicloudReport : NSObject
{
}

+ (long long)convertStrToStatus:(id)arg1;
+ (id)convertStatusToStr:(long long)arg1;
+ (id)convertTagToStr:(long long)arg1;
+ (id)assembleContentBody:(id)arg1 utdid:(id)arg2 extInfo:(id)arg3;
+ (_Bool)sendRequest:(id)arg1 extInfo:(id)arg2;
+ (void)reportWithRetryCategory:(id)arg1 extInfo:(id)arg2;
+ (void)statAsync:(long long)arg1 extInfo:(id)arg2;
+ (void)statAsync:(long long)arg1;
+ (long long)getReportStatus:(long long)arg1;
+ (_Bool)isDeviceReported:(long long)arg1;
+ (void)initialize;

@end

