//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface AppMonitorEvent : NSObject
{
    NSString *_module;
    NSString *_monitorPoint;
    NSString *_eventId;
    NSDictionary *_extraInfo;
}

@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(retain, nonatomic) NSString *eventId; // @synthesize eventId=_eventId;
@property(retain, nonatomic) NSString *monitorPoint; // @synthesize monitorPoint=_monitorPoint;
@property(retain, nonatomic) NSString *module; // @synthesize module=_module;
- (void).cxx_destruct;
- (id)jsonDict;
- (id)initWithEventId:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3 extraInfo:(id)arg4;
- (id)initWithEventId:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3;

@end

