//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorDimensionValueSet.h"

@class NSMutableDictionary;

@interface AppMonitorUTDimensionValueSet : AppMonitorDimensionValueSet
{
    NSMutableDictionary *_rawMessageDict;
}

@property(retain, nonatomic) NSMutableDictionary *rawMessageDict; // @synthesize rawMessageDict=_rawMessageDict;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)eventId;
- (id)initWithDictionary:(id)arg1;
- (id)initWithEvent:(id)arg1;
- (id)initWithEventId:(id)arg1;

@end

