//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaiduMobAdLpTintStyle;

@interface BaiduMobAdProgressBar : UIView
{
    float _progress;
    BaiduMobAdLpTintStyle *_style;
}

@property(retain, nonatomic) BaiduMobAdLpTintStyle *style; // @synthesize style=_style;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;

@end

