//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdNativeVideoBaseView.h"

@class AVPlayer, AVPlayerLayer, BaiduMobAdNativeAdObject, NSString, NSTimer, NSURL, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UISlider, UITapGestureRecognizer, UIView;

@interface BaiduMobAdNativeVideoView : BaiduMobAdNativeVideoBaseView
{
    int _state;
    _Bool _supportControllerView;
    _Bool _supportActImage;
    _Bool _isFullScreen;
    _Bool _isFirstTimePlay;
    _Bool _metaLoaded;
    _Bool _isAutoPlay;
    _Bool _isVideo;
    int _remainTimeValue;
    UIButton *_btnLP;
    UISlider *_progress;
    UIButton *_btnPlayOrPause;
    UIButton *_btnFullScreen;
    UIButton *_btnDone;
    UIView *_controlView;
    UIActivityIndicatorView *_indicatorView;
    BaiduMobAdNativeAdObject *_associatedObject;
    UIView *_displayView;
    UIView *_floatView;
    NSURL *_url;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    UITapGestureRecognizer *_tapGesture;
    UIView *_originSuperView;
    id _playbackObserver;
    NSTimer *_countTimer;
    UILabel *_timecountLabel;
    UIImageView *_endcardview;
    NSString *_endcardUrlString;
    NSString *_mainImageUrl;
    struct CGRect _originFrame;
}

@property(retain, nonatomic) NSString *mainImageUrl; // @synthesize mainImageUrl=_mainImageUrl;
@property(nonatomic) _Bool isVideo; // @synthesize isVideo=_isVideo;
@property(nonatomic) _Bool isAutoPlay; // @synthesize isAutoPlay=_isAutoPlay;
@property(retain, nonatomic) NSString *endcardUrlString; // @synthesize endcardUrlString=_endcardUrlString;
@property(retain, nonatomic) UIImageView *endcardview; // @synthesize endcardview=_endcardview;
@property(retain, nonatomic) UILabel *timecountLabel; // @synthesize timecountLabel=_timecountLabel;
@property(nonatomic) int remainTimeValue; // @synthesize remainTimeValue=_remainTimeValue;
@property(retain, nonatomic) NSTimer *countTimer; // @synthesize countTimer=_countTimer;
@property(retain, nonatomic) id playbackObserver; // @synthesize playbackObserver=_playbackObserver;
@property(nonatomic) UIView *originSuperView; // @synthesize originSuperView=_originSuperView;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) UIView *floatView; // @synthesize floatView=_floatView;
@property(retain, nonatomic) UIView *displayView; // @synthesize displayView=_displayView;
@property(retain, nonatomic) BaiduMobAdNativeAdObject *associatedObject; // @synthesize associatedObject=_associatedObject;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
@property(nonatomic) _Bool metaLoaded; // @synthesize metaLoaded=_metaLoaded;
@property(nonatomic) _Bool isFirstTimePlay; // @synthesize isFirstTimePlay=_isFirstTimePlay;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(retain, nonatomic) UIView *controlView; // @synthesize controlView=_controlView;
@property(retain, nonatomic) UIButton *btnDone; // @synthesize btnDone=_btnDone;
@property(retain, nonatomic) UIButton *btnFullScreen; // @synthesize btnFullScreen=_btnFullScreen;
@property(retain, nonatomic) UIButton *btnPlayOrPause; // @synthesize btnPlayOrPause=_btnPlayOrPause;
@property(retain, nonatomic) UISlider *progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIButton *btnLP; // @synthesize btnLP=_btnLP;
@property _Bool supportActImage; // @synthesize supportActImage=_supportActImage;
@property _Bool supportControllerView; // @synthesize supportControllerView=_supportControllerView;
- (void).cxx_destruct;
- (_Bool)handleScrollStop;
- (void)didMoveToWindow;
- (void)sendVideoEvent:(int)arg1 currentTime:(double)arg2;
- (void)updateValue:(id)arg1;
- (void)addProgressObserver;
- (void)videoAdClick;
- (void)btnLPClick;
- (void)clickFullScreen:(id)arg1;
- (void)playClick:(id)arg1;
- (_Bool)newWindowTransform;
- (void)didChangeOrientation;
- (void)handleClick;
- (_Bool)isPlaying;
- (void)playbackFail:(id)arg1;
- (void)onPlaybackLikelyToKeepUpChange;
- (void)onPlayerRateChange;
- (void)setRemainTime;
- (void)layoutDisplayArea;
- (void)displayVideo;
- (void)completePlayback;
- (void)startPlayback;
- (void)hideActionButton;
- (void)showActionButton;
- (void)hideEndCard;
- (void)showEndCard;
- (void)onPlayerItemDidReachEnd:(id)arg1;
- (void)onPlayerItemFail:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)resizePlaybackFrame:(struct CGRect)arg1;
- (double)currentTime;
- (double)duration;
- (_Bool)render;
- (void)stop;
- (void)pause;
- (void)play;
- (void)handleTapGesture:(id)arg1;
- (void)checkVisible;
- (id)imageForString:(id)arg1;
- (void)setupUI;
- (void)cleanUp;
- (void)dealloc;
- (void)setupImageUI;
- (id)initImageWithFrame:(struct CGRect)arg1 andObject:(id)arg2;
- (id)initVideoWithFrame:(struct CGRect)arg1 andObject:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 andObject:(id)arg2;

@end

