//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XNonLinearAdSlot.h"

@interface BaiduMobAdBannerSlot : XNonLinearAdSlot
{
}

- (id)buildFixedResponse;
- (void)successCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
- (void)request;
- (id)type;
- (void)start;
- (void)dealloc;
- (id)init;

@end

