//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DRAgentMediaDownloaderDelegate.h"

@class AVAssetResourceLoadingRequest, DRAgentMediaDownloader, NSString;

@interface DRAgentResourceLoadingRequestWorker : NSObject <DRAgentMediaDownloaderDelegate>
{
    id <DRAgentResourceLoadingRequestWorkerDelegate> _delegate;
    AVAssetResourceLoadingRequest *_request;
    DRAgentMediaDownloader *_mediaDownloader;
}

@property(retain, nonatomic) DRAgentMediaDownloader *mediaDownloader; // @synthesize mediaDownloader=_mediaDownloader;
@property(retain, nonatomic) AVAssetResourceLoadingRequest *request; // @synthesize request=_request;
@property(nonatomic) __weak id <DRAgentResourceLoadingRequestWorkerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mediaDownloader:(id)arg1 didFinishedWithError:(id)arg2;
- (void)mediaDownloader:(id)arg1 didReceiveData:(id)arg2;
- (void)mediaDownloader:(id)arg1 didReceiveResponse:(id)arg2;
- (void)fullfillContentInfo;
- (id)loaderCancelledError;
- (void)finish;
- (void)cancel;
- (void)startWork;
- (id)initWithMediaDownloader:(id)arg1 resourceLoadingRequest:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

