//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface GDTAdLifeEvent : NSObject
{
    int _type;
    NSDictionary *_params;
}

+ (int)convertLifeEventTypeFromString:(id)arg1;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(int)arg1 Params:(id)arg2;

@end

