//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface GDTContentInfo : NSObject <NSCoding>
{
    _Bool _byteRangeAccessSupported;
    NSString *_contentType;
    unsigned long long _contentLength;
    unsigned long long _downloadedContentLength;
}

@property(nonatomic) unsigned long long downloadedContentLength; // @synthesize downloadedContentLength=_downloadedContentLength;
@property(nonatomic) unsigned long long contentLength; // @synthesize contentLength=_contentLength;
@property(nonatomic) _Bool byteRangeAccessSupported; // @synthesize byteRangeAccessSupported=_byteRangeAccessSupported;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)debugDescription;

@end

