//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDTEvent : NSObject
{
}

+ (void)onDidApplicationBecomeActive;
+ (void)onWillApplicationEnterBackground;
+ (void)recordLog:(id)arg1 level:(long long)arg2 customId:(long long)arg3;
+ (void)recordLog:(id)arg1 level:(long long)arg2;
+ (void)recordLog:(id)arg1;
+ (void)endEventId:(long long)arg1 ext:(id)arg2;
+ (void)beginEventId:(long long)arg1;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 ext:(id)arg3;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2;
+ (void)recordEventId:(long long)arg1;
+ (void)registerEvent;

@end

