//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GDTLoadAdRequestExtData : NSObject
{
    _Bool _tmpallpt;
    _Bool _c_isjailbroken;
    _Bool _supportVideo;
    int _c_devicetype;
    int _c_ori;
    int _c_w;
    int _c_h;
    int _c_dpi;
    int _muidtype;
    int _conn;
    int _carrier;
    int _deep_link_version;
    NSString *_c_device;
    NSString *_c_pkgname;
    NSString *_muid;
    double _lat;
    double _lng;
    double _loc_accuracy;
    NSString *_c_osver;
    NSString *_c_os;
    NSString *_sdkver;
    long long _c_sdfree;
    NSString *_sdk_src;
    NSString *_m5;
    NSString *_m6;
    NSString *_m7;
    NSString *_lg;
    NSString *_nativeJsVersion;
}

@property(nonatomic) _Bool supportVideo; // @synthesize supportVideo=_supportVideo;
@property(copy, nonatomic) NSString *nativeJsVersion; // @synthesize nativeJsVersion=_nativeJsVersion;
@property(copy, nonatomic) NSString *lg; // @synthesize lg=_lg;
@property(copy, nonatomic) NSString *m7; // @synthesize m7=_m7;
@property(copy, nonatomic) NSString *m6; // @synthesize m6=_m6;
@property(copy, nonatomic) NSString *m5; // @synthesize m5=_m5;
@property(copy, nonatomic) NSString *sdk_src; // @synthesize sdk_src=_sdk_src;
@property(nonatomic) long long c_sdfree; // @synthesize c_sdfree=_c_sdfree;
@property(nonatomic) int deep_link_version; // @synthesize deep_link_version=_deep_link_version;
@property(nonatomic) _Bool c_isjailbroken; // @synthesize c_isjailbroken=_c_isjailbroken;
@property(nonatomic) _Bool tmpallpt; // @synthesize tmpallpt=_tmpallpt;
@property(copy, nonatomic) NSString *sdkver; // @synthesize sdkver=_sdkver;
@property(copy, nonatomic) NSString *c_os; // @synthesize c_os=_c_os;
@property(copy, nonatomic) NSString *c_osver; // @synthesize c_osver=_c_osver;
@property(nonatomic) double loc_accuracy; // @synthesize loc_accuracy=_loc_accuracy;
@property(nonatomic) double lng; // @synthesize lng=_lng;
@property(nonatomic) double lat; // @synthesize lat=_lat;
@property(nonatomic) int carrier; // @synthesize carrier=_carrier;
@property(nonatomic) int conn; // @synthesize conn=_conn;
@property(nonatomic) int muidtype; // @synthesize muidtype=_muidtype;
@property(copy, nonatomic) NSString *muid; // @synthesize muid=_muid;
@property(copy, nonatomic) NSString *c_pkgname; // @synthesize c_pkgname=_c_pkgname;
@property(nonatomic) int c_dpi; // @synthesize c_dpi=_c_dpi;
@property(nonatomic) int c_h; // @synthesize c_h=_c_h;
@property(nonatomic) int c_w; // @synthesize c_w=_c_w;
@property(nonatomic) int c_ori; // @synthesize c_ori=_c_ori;
@property(nonatomic) int c_devicetype; // @synthesize c_devicetype=_c_devicetype;
@property(copy, nonatomic) NSString *c_device; // @synthesize c_device=_c_device;
- (void).cxx_destruct;
- (id)toMap;

@end

