//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GDTNativeExpressAd : NSObject
{
    _Bool _videoAutoPlayOnWWAN;
    _Bool _videoMuted;
    id <GDTNativeExpressAdDelegete> _delegate;
    NSString *_placementId;
    NSString *_appId;
    NSString *_threadId;
    struct CGSize _adSize;
}

@property(nonatomic) struct CGSize adSize; // @synthesize adSize=_adSize;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(nonatomic) _Bool videoMuted; // @synthesize videoMuted=_videoMuted;
@property(nonatomic) _Bool videoAutoPlayOnWWAN; // @synthesize videoAutoPlayOnWWAN=_videoAutoPlayOnWWAN;
@property(nonatomic) __weak id <GDTNativeExpressAdDelegete> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithAppkey:(id)arg1 placementId:(id)arg2 adSize:(struct CGSize)arg3;
- (void)showError:(unsigned long long)arg1 detailErrorCode:(unsigned long long)arg2;
- (void)showError:(unsigned long long)arg1;
- (_Bool)checkParams;
- (void)loadAd:(long long)arg1;
- (void)initAdMgr;
- (id)initWithAppId:(id)arg1 placementId:(id)arg2 adSize:(struct CGSize)arg3;

@end

