//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTAdLifeEventListener.h"

@class GDTNativeExpressAdView, NSString;

@interface GDTNativeExpressLifeCycleStateListener : NSObject <GDTAdLifeEventListener>
{
    id <GDTNativeExpressAdDelegete> _delegate;
    GDTNativeExpressAdView *_nativeExpressView;
}

@property(nonatomic) __weak GDTNativeExpressAdView *nativeExpressView; // @synthesize nativeExpressView=_nativeExpressView;
@property(nonatomic) __weak id <GDTNativeExpressAdDelegete> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showError:(unsigned long long)arg1 detailCode:(unsigned long long)arg2;
- (void)onEvent:(id)arg1;
- (id)initWithNativeExpressView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

