//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GDTTrackingInfoService : NSObject
{
}

+ (id)sharedInstance;
- (id)standardFormateMAC:(id)arg1;
@property(readonly, nonatomic) NSString *wifiBSSID;
@property(readonly, nonatomic) NSString *wifiSSID;
@property(readonly, nonatomic) long long networkCondition;
@property(readonly, nonatomic) NSString *term;
@property(readonly, nonatomic) NSString *appName;
@property(readonly, nonatomic) NSString *appKey;
@property(readonly, nonatomic) NSString *scwh;
@property(readonly, nonatomic) NSString *systemVerstion;
- (id)ipAddress;
- (id)macAddress;

@end

