//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface IMContentSaveResult : NSObject
{
    _Bool _saveContentStatus;
    int _errorCode;
    NSMutableDictionary *_resultDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *resultDictionary; // @synthesize resultDictionary=_resultDictionary;
@property(nonatomic) _Bool saveContentStatus; // @synthesize saveContentStatus=_saveContentStatus;
@property(nonatomic) int errorCode; // @synthesize errorCode=_errorCode;
- (void).cxx_destruct;

@end

