//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIActionSheetDelegate.h"

@class NSString, UIActionSheet, UIBarButtonItem, UIToolbar, UIWebView;

@interface IMEmbeddedBrowser : UIViewController <UIActionSheetDelegate>
{
    UIBarButtonItem *safari;
    UIBarButtonItem *back;
    UIBarButtonItem *forward;
    UIBarButtonItem *reload;
    UIBarButtonItem *close;
    UIBarButtonItem *bar;
    UIToolbar *_bar;
    UIActionSheet *_actionSheet;
    UIWebView *_webView;
    id <IMEmbeddedBrowserDelegate> _delegate;
}

@property(nonatomic) __weak id <IMEmbeddedBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) UIActionSheet *actionSheet; // @synthesize actionSheet=_actionSheet;
@property(retain, nonatomic) UIToolbar *bar; // @synthesize bar=_bar;
@property(retain, nonatomic) UIBarButtonItem *close; // @synthesize close;
@property(retain, nonatomic) UIBarButtonItem *reload; // @synthesize reload;
@property(retain, nonatomic) UIBarButtonItem *forward; // @synthesize forward;
@property(retain, nonatomic) UIBarButtonItem *back; // @synthesize back;
@property(retain, nonatomic) UIBarButtonItem *safari; // @synthesize safari;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (struct CGImage *)newBackButtonIcon;
- (struct CGImage *)newCloseButtonIcon;
- (struct CGImage *)newForwardButtonIcon;
- (struct CGContext *)newContext;
- (void)viewWillAppear:(_Bool)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)handleLinkClicked:(id)arg1;
- (void)closeEmbeddedBrowser;
- (void)goBack;
- (void)goFwd;
- (void)refresh;
- (void)openSafari;
- (id)flexiSpaceButton;
- (id)backButton;
- (id)closeButton;
- (id)forwardButton;
- (id)reloadButton;
- (id)safariButton;
- (void)dealloc;
- (void)checkButtonAction;
- (void)loadRequest:(id)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

