//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMBaseProcessor.h"

@class IMPingStore;

@interface IMPingProcessor : IMBaseProcessor
{
    IMPingStore *_pingstore;
}

@property(retain, nonatomic) IMPingStore *pingstore; // @synthesize pingstore=_pingstore;
- (void).cxx_destruct;
- (void)pingWithParams:(id)arg1 withScheme:(id)arg2 inWebView:(_Bool)arg3 command:(id)arg4;

@end

