//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMConfigDelegate.h"

@class IMAdsConfig, IMPlacementDao, NSString;

@interface IMPlacementCache : NSObject <IMConfigDelegate>
{
    IMPlacementDao *_placementDao;
    IMAdsConfig *_adsConfig;
}

+ (id)sharedCache;
@property(retain, nonatomic) IMAdsConfig *adsConfig; // @synthesize adsConfig=_adsConfig;
@property(retain, nonatomic) IMPlacementDao *placementDao; // @synthesize placementDao=_placementDao;
- (void).cxx_destruct;
- (void)configUpdated:(id)arg1;
- (void)removeAllPlacements;
- (void)sendTelemetryEventForPlacementExpiry:(long long)arg1;
- (void)sendTelemetryEventForOverflow:(long long)arg1;
- (void)cleanupCache;
- (void)stop;
- (void)start;
- (void)updateMetadata:(long long)arg1 withAdType:(id)arg2 withExtras:(id)arg3;
- (id)getAllPlacementIDs:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

