//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAsset.h"

@interface IMTextAsset : IMAsset
{
}

- (void)updatePropertiesOnView;
- (id)createViewWithProperties:(id)arg1;
- (_Bool)isStyleValid;
- (void)recycleView;
- (id)buildAssetViewWithScale:(double)arg1;
- (void)fetchAssetResources;

@end

