//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAsset.h"

@class IMUITimerProperties, NSDictionary, NSString;

@interface IMTimerAsset : IMAsset
{
    _Bool _displayTimer;
    IMUITimerProperties *properties;
    NSString *_timerAction;
    double _timerStartOffset;
    double _timerDuration;
    NSDictionary *_startOffsetDictionary;
    NSDictionary *_durationDictionary;
}

@property(retain, nonatomic) NSDictionary *durationDictionary; // @synthesize durationDictionary=_durationDictionary;
@property(retain, nonatomic) NSDictionary *startOffsetDictionary; // @synthesize startOffsetDictionary=_startOffsetDictionary;
@property(nonatomic) double timerDuration; // @synthesize timerDuration=_timerDuration;
@property(nonatomic) double timerStartOffset; // @synthesize timerStartOffset=_timerStartOffset;
@property(retain, nonatomic) NSString *timerAction; // @synthesize timerAction=_timerAction;
@property(nonatomic) _Bool displayTimer; // @synthesize displayTimer=_displayTimer;
@property(retain, nonatomic) IMUITimerProperties *properties; // @synthesize properties;
- (void).cxx_destruct;
- (void)updatePropertiesOnView;
- (id)createViewWithProperties:(id)arg1;
- (void)generateProperties:(id)arg1 fromJson:(id)arg2;
- (id)propertiesFromJson:(id)arg1;
- (void)fetchAssetResources;
- (void)recycleView;
- (id)buildAssetViewWithScale:(double)arg1;
- (void)resetAssetAndRebuild:(_Bool)arg1;
- (double)timeFromDictionary:(id)arg1 withDefaultValue:(double)arg2;
- (void)timerExpired:(id)arg1;
- (id)initWithJson:(id)arg1 withStyles:(id)arg2 atJPath:(id)arg3;

@end

