//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMVastObject.h"

@class NSString;

@interface IMVastMediaFile : IMVastObject
{
    _Bool _maintainAspectRatio;
    NSString *_url;
    double _bitrate;
    long long _mediaFileType;
    NSString *_type;
    struct CGSize _videoSize;
}

@property(readonly) _Bool maintainAspectRatio; // @synthesize maintainAspectRatio=_maintainAspectRatio;
@property(readonly) NSString *type; // @synthesize type=_type;
@property(readonly) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(readonly) long long mediaFileType; // @synthesize mediaFileType=_mediaFileType;
@property(readonly) double bitrate; // @synthesize bitrate=_bitrate;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

