//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "InMobi_InternalAvidAdSession.h"

@class UIWebView;

@interface InMobi_InternalAvidManagedAdSession : InMobi_InternalAvidAdSession
{
    UIWebView *_webView;
}

- (void).cxx_destruct;
- (void)onStart;

@end

