//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class InMobi_AvidEvent, NSMutableArray;

@interface InMobi_AvidEventDispatcher : NSObject
{
    _Bool _shouldWaitForReadyEvent;
    id <InMobi_AvidEventDispatcherDelegate> _delegate;
    InMobi_AvidEvent *_readyEvent;
    NSMutableArray *_eventBuffer;
}

@property(retain, nonatomic) NSMutableArray *eventBuffer; // @synthesize eventBuffer=_eventBuffer;
@property(nonatomic) _Bool shouldWaitForReadyEvent; // @synthesize shouldWaitForReadyEvent=_shouldWaitForReadyEvent;
@property(retain, nonatomic) InMobi_AvidEvent *readyEvent; // @synthesize readyEvent=_readyEvent;
@property(nonatomic) __weak id <InMobi_AvidEventDispatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)assertReadyEventReceived;
- (void)assertReadyEventAllowed;
- (void)assertItIsTheFirstReadyEvent;
- (void)pushBufferToDelegate;
- (void)forwardEventsFromBufferToDelegate;
- (void)postEvent:(id)arg1;
@property(readonly, nonatomic) _Bool isReadyEventReceived;
- (id)initWithShouldWaitForReadyEvent:(_Bool)arg1;

@end

