//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JPUSHTcpSocketDelegate.h"

@class JPUSHAddressController, JPUSHFIFOQueue, JPUSHLoginRequest, JPUSHTcpSocket, NSArray, NSMutableArray, NSString, NSTimer;

@interface JPUSHSessionController : NSObject <JPUSHTcpSocketDelegate>
{
    JPUSHAddressController *_addressController;
    int _proofTimeInterval;
    unsigned short _serverVersion;
    unsigned long long _rId;
    NSString *_sessionKey;
    JPUSHLoginRequest *_loginRequest;
    JPUSHTcpSocket *_tcpConnectionSocket;
    JPUSHFIFOQueue *_tcpBlockedQueue;
    JPUSHFIFOQueue *_tcpSendingQueue;
    NSTimer *_heartbeatTimer;
    unsigned long long _delaySetupTimeIntervalIndex;
    NSTimer *_delaySetupTimer;
    int _status;
    double _lastSucceedSisTime;
    _Bool _isConnecting;
    _Bool _hasCloseSession;
    _Bool _isSetup;
    _Bool _isLogin;
    _Bool _isConnected;
    unsigned int _sessionID;
    NSMutableArray *_timeoutCallbacks;
    NSArray *_sisContent;
}

@property(retain, nonatomic) NSArray *sisContent; // @synthesize sisContent=_sisContent;
@property(readonly, nonatomic) NSMutableArray *timeoutCallbacks; // @synthesize timeoutCallbacks=_timeoutCallbacks;
@property(readonly, nonatomic) int proofTimeInterval; // @synthesize proofTimeInterval=_proofTimeInterval;
@property(readonly, nonatomic) JPUSHAddressController *addressController; // @synthesize addressController=_addressController;
@property(readonly, nonatomic) unsigned long long rId; // @synthesize rId=_rId;
@property(readonly, nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(readonly, nonatomic) _Bool isConnected; // @synthesize isConnected=_isConnected;
@property(readonly, nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
@property(readonly, nonatomic) _Bool isSetup; // @synthesize isSetup=_isSetup;
- (void).cxx_destruct;
- (void)saveDefaultConnInfo:(id)arg1;
- (void)clearDefaultConnInfo;
- (void)resetSisCache;
- (_Bool)isNetworkChanged;
- (_Bool)isLastSisTooLong;
- (void)stopDelaySetupTimer;
- (void)startDelaySetupTimer;
- (void)doDelaySetup:(id)arg1;
- (void)heartAck;
- (void)stopHeartbeatTimer;
- (void)removeHeartBeatLock;
- (void)fireHeartBeat;
- (void)doHeartbeat:(id)arg1;
- (void)startHeartbeatTimer;
- (void)addTimeoutCallback:(CDUnknownBlockType)arg1;
- (void)onAckTimeoutForRequest:(id)arg1;
- (void)onAckOrRespReceived:(id)arg1;
- (void)onLoginRespond:(id)arg1;
- (void)doLogin;
- (_Bool)clientStateWithError:(unsigned short)arg1;
- (void)onRegisterRespond:(id)arg1;
- (void)doRegister;
- (void)doRegisterOrLogin;
- (void)reenqueueSendingRequests;
- (id)findSendingRequest:(unsigned long long)arg1;
- (id)findBlockedRequest:(unsigned long long)arg1;
- (void)dequeueRequest:(id)arg1;
- (void)enqueueRequest:(id)arg1;
- (void)connectionSendQueueEmpty:(id)arg1;
- (void)connection:(id)arg1 didSendData:(id)arg2;
- (void)connection:(id)arg1 didReceiveElement:(id)arg2;
- (void)connectionDidFailed:(struct __CFData *)arg1;
- (void)connectionDidClose:(id)arg1;
- (void)connectionDidSetup:(id)arg1;
- (void)doSendTcpRequest:(id)arg1;
- (void)sendRequest:(id)arg1;
- (_Bool)isSisOnProtect;
- (_Bool)connectTcpAddress:(id)arg1;
- (_Bool)connectTcp:(id)arg1;
- (_Bool)connect;
- (_Bool)connectWithTcpCoreAddress:(id)arg1;
- (unsigned long long)getRId:(unsigned long long)arg1;
- (void)manualClose;
- (_Bool)close;
- (void)netWorkChange;
- (void)resetDelaySetupIndex;
- (void)setup;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

