//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JPUSHAES : NSObject
{
}

+ (id)encryptData:(id)arg1 withKeyRef:(struct __SecKey *)arg2;
+ (id)stripPublicKeyHeader:(id)arg1;
+ (struct __SecKey *)addPublicKey:(id)arg1;
+ (id)rsaEncrypt:(id)arg1 publicKey:(id)arg2;
+ (id)sha1:(id)arg1;
+ (id)generateSeedKey:(unsigned long long)arg1;
+ (id)encryptKeyForHttp;
+ (id)encryptSisKeyWithSeed:(unsigned long long)arg1;
+ (id)encryptKeyWithSeed:(unsigned long long)arg1;
+ (id)doCryptWith:(id)arg1 key:(id)arg2 keyLen:(unsigned long long)arg3 operation:(unsigned int)arg4 options:(unsigned int)arg5 iv:(const void *)arg6;
+ (id)aes256DecryptData:(id)arg1 withKey:(id)arg2;
+ (id)aes256CBCEncryptData:(id)arg1 withKey:(id)arg2;
+ (id)aes256EncryptData:(id)arg1 withKey:(id)arg2;
+ (id)aes256EncryptData:(id)arg1 withKey:(id)arg2 iv:(const char *)arg3;
+ (id)AES256DecryptData:(id)arg1 withKey:(id)arg2;
+ (id)AES256EncryptData:(id)arg1 withKey:(id)arg2;
+ (id)encrypt:(id)arg1 aesKey:(id)arg2;
+ (id)decrypt:(id)arg1 aesKey:(id)arg2;
+ (id)encryptDataTypeToCurrentStringType:(id)arg1;
+ (id)sharedAESUtils;
- (id)doCipher:(id)arg1 key:(id)arg2 context:(unsigned int)arg3 padding:(unsigned int *)arg4;
- (id)decrypt:(id)arg1 key:(id)arg2 padding:(unsigned int *)arg3;
- (id)encrypt:(id)arg1 key:(id)arg2 padding:(unsigned int *)arg3;

@end

