//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSDictionary, NSMutableArray, NSMutableData, NSMutableDictionary, NSMutableURLRequest, NSString, NSTimer;

@interface JPUSHReportRequest : NSObject
{
    NSMutableDictionary *_reportBody;
    NSTimer *_reportWaitTimer;
    long long _reportTimeStamp;
    _Bool _hasSubpackage;
    unsigned char _controlFlag;
    _Bool _isResend;
    _Bool _reportNeedDelay;
    CDUnknownBlockType _completion;
    NSMutableData *_packetValueData;
    NSString *_reportFlag;
    unsigned long long _reportType;
    NSMutableArray *_reportContents;
    NSMutableArray *_realContents;
    NSDictionary *_content;
    CDUnknownBlockType _responseBlock;
    NSData *_bodyData;
    NSString *_aesKey;
    long long _reSendTimerIndex;
    NSArray *_reportAddressList;
    NSMutableURLRequest *_request;
}

@property(copy, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSArray *reportAddressList; // @synthesize reportAddressList=_reportAddressList;
@property(readonly, nonatomic) _Bool reportNeedDelay; // @synthesize reportNeedDelay=_reportNeedDelay;
@property(nonatomic) _Bool isResend; // @synthesize isResend=_isResend;
@property(nonatomic) long long reSendTimerIndex; // @synthesize reSendTimerIndex=_reSendTimerIndex;
@property(readonly, copy, nonatomic) NSString *aesKey; // @synthesize aesKey=_aesKey;
@property(retain, nonatomic) NSData *bodyData; // @synthesize bodyData=_bodyData;
@property(copy, nonatomic) CDUnknownBlockType responseBlock; // @synthesize responseBlock=_responseBlock;
@property(retain, nonatomic) NSDictionary *content; // @synthesize content=_content;
@property(retain, nonatomic) NSMutableArray *realContents; // @synthesize realContents=_realContents;
@property(retain, nonatomic) NSMutableArray *reportContents; // @synthesize reportContents=_reportContents;
@property(nonatomic) long long reportTimeStamp; // @synthesize reportTimeStamp=_reportTimeStamp;
@property(nonatomic) unsigned long long reportType; // @synthesize reportType=_reportType;
@property(retain, nonatomic) NSString *reportFlag; // @synthesize reportFlag=_reportFlag;
@property(nonatomic) unsigned char controlFlag; // @synthesize controlFlag=_controlFlag;
@property(retain, nonatomic) NSMutableData *packetValueData; // @synthesize packetValueData=_packetValueData;
@property(readonly, nonatomic) _Bool hasSubpackage; // @synthesize hasSubpackage=_hasSubpackage;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (id)description;
- (_Bool)p_checkTimestampLength:(long long)arg1;
- (void)writeToCache;
- (id)p_generateRequestHead;
- (id)generateReportRequest;
- (void)cancelDelayTimer;
- (void)startDelayTimerWithHandler:(CDUnknownBlockType)arg1;
- (void)endDelayTimer:(id)arg1;
- (void)addDelayTimerWithHandler:(CDUnknownBlockType)arg1;
- (void)send;
- (_Bool)startDelaySend;
@property(nonatomic) _Bool isSendRequestLock; // @dynamic isSendRequestLock;
- (_Bool)accountIDRequired;
- (_Bool)cacheRequestRequired;
- (_Bool)loginRequired;
- (_Bool)validRequired;
- (_Bool)packData;
- (_Bool)compareInfoFrom:(id)arg1 To:(id)arg2;
- (id)generateSessionId:(long long)arg1;
- (id)generateSessionId;
- (id)historyFileCache;
- (void)p_addHistoryFile;
- (unsigned long long)p_calculateCurrentSize;
- (void)p_addContents;
- (void)p_dropContentBeyondMaxSize;
- (id)packetData;
- (void)setResponseBlock;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

