//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface LehooLocalConnection : NSObject
{
    _Bool _isReachable;
    struct __SCNetworkReachability *_reachabilityRef;
    NSObject<OS_dispatch_queue> *_reachabilitySerialQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *reachabilitySerialQueue; // @synthesize reachabilitySerialQueue=_reachabilitySerialQueue;
@property(nonatomic) struct __SCNetworkReachability *reachabilityRef; // @synthesize reachabilityRef=_reachabilityRef;
@property(nonatomic) _Bool isReachable; // @synthesize isReachable=_isReachable;
- (void).cxx_destruct;
- (_Bool)isReachableViaWiFi;
- (_Bool)isReachableViaWWAN;
- (_Bool)isReachableWithFlags:(unsigned int)arg1;
- (_Bool)_isReachable;
- (unsigned int)reachabilityFlags;
- (id)currentConnectionFlags;
- (void)localConnectionChanged;
- (long long)currentLehooLocalConnectionStatus;
- (void)stopNotifier;
- (void)startNotifier;
- (void)dealloc;
- (id)init;

@end

