//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YYModel.h"

@class NSArray, NSString;

@interface LZMBeautyModel : NSObject <YYModel>
{
    long long _liveTotal;
    NSArray *_roomList;
    long long _roomTotal;
    long long _totalpage;
    long long _pagesize;
    long long _page;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) long long pagesize; // @synthesize pagesize=_pagesize;
@property(nonatomic) long long totalpage; // @synthesize totalpage=_totalpage;
@property(nonatomic) long long roomTotal; // @synthesize roomTotal=_roomTotal;
@property(retain, nonatomic) NSArray *roomList; // @synthesize roomList=_roomList;
@property(nonatomic) long long liveTotal; // @synthesize liveTotal=_liveTotal;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

