//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMAdBaseManager.h"

#import "CSVideoADDelegate.h"

@class NSString;

@interface LZMChanceManager : LZMAdBaseManager <CSVideoADDelegate>
{
}

+ (id)sharedInstance;
- (void)startInterstitialAd:(id)arg1 inRect:(struct CGRect)arg2;
- (void)removeCurrentAdORStopAd:(id)arg1;
- (id)getPlaceIdFormCurrentNative:(id)arg1;
- (void)prollAdTimeOutAction;
- (void)backBtnClick:(id)arg1;
- (void)addBackBtnAndTimeLabel:(id)arg1;
- (void)activeProllAdBaseBiew:(id)arg1 withObject:(id)arg2 andPlaceId:(long long)arg3 andADtype:(long long)arg4;
- (void)activeNativeAdBaseBiew:(id)arg1 withObject:(id)arg2 andPlaceId:(long long)arg3 andADtype:(long long)arg4;
- (void)startNativeAd:(long long)arg1;
- (void)startSplashAd;
- (void)csVideoADClosed:(id)arg1;
- (void)csVideoAD:(id)arg1 clickDownload:(_Bool)arg2;
- (void)csVideoAD:(id)arg1 playVideoFinished:(_Bool)arg2;
- (void)csVideoAD:(id)arg1 clickCloseButtonAndWillClose:(_Bool)arg2;
- (void)csVideoAD:(id)arg1 showVideoADSuccess:(_Bool)arg2;
- (void)csVideoAD:(id)arg1 showVideoADError:(id)arg2;
- (void)csVideoAD:(id)arg1 cancelPlayWithError:(id)arg2;
- (void)csVideoADExitPlayWhenLoading:(id)arg1;
- (_Bool)csVideoADWillPlayVideoAD:(id)arg1;
- (void)csVideoAD:(id)arg1 videoFileIsReady:(_Bool)arg2;
- (void)csVideoAD:(id)arg1 requestVideoADError:(id)arg2;
- (void)csVideoADRequestVideoADSuccess:(id)arg1;
- (void)startVideoAdWithPresentVC:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

