//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface LZMFProSearchView : UIView
{
    UILabel *_searchLabel;
    UIActivityIndicatorView *_deviceActivityView;
}

@property(retain, nonatomic) UIActivityIndicatorView *deviceActivityView; // @synthesize deviceActivityView=_deviceActivityView;
@property(retain, nonatomic) UILabel *searchLabel; // @synthesize searchLabel=_searchLabel;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)setHidden:(_Bool)arg1;
- (id)init;

@end

