//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LZMFileMoveManager : NSObject
{
}

+ (id)shareInstance;
- (id)getVideoIdandNumberFromTargetId:(id)arg1;
- (id)backDefinitionStringFromNumber:(long long)arg1;
- (void)getFilePathAndReplaced:(id)arg1;
- (void)getTargetNoticeM3u8:(id)arg1;
- (void)repairMyM3u8Files;
- (void)moveFiles;
- (void)saveToSQLWithArr:(id)arg1;
- (void)readFileBeforeUpdate;

@end

