//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "M3U8PraseDelegate.h"
#import "NSURLSessionDelegate.h"

@class LZMDownloadModel, NSString, NSTimer;

@interface LZMFPraserManager : NSObject <M3U8PraseDelegate, NSURLSessionDelegate>
{
    _Bool _rePraserTimes;
    _Bool _isTimeOutNow;
    LZMDownloadModel *_currentModel;
    NSTimer *_praserTimer;
    CDUnknownBlockType _complete;
}

+ (id)shareInstance;
@property(copy, nonatomic) CDUnknownBlockType complete; // @synthesize complete=_complete;
@property(nonatomic) _Bool isTimeOutNow; // @synthesize isTimeOutNow=_isTimeOutNow;
@property(retain, nonatomic) NSTimer *praserTimer; // @synthesize praserTimer=_praserTimer;
@property(retain, nonatomic) LZMDownloadModel *currentModel; // @synthesize currentModel=_currentModel;
@property(nonatomic) _Bool rePraserTimes; // @synthesize rePraserTimes=_rePraserTimes;
- (void).cxx_destruct;
- (void)timeoutIntervalForPraser;
- (void)alreadyPraserModel:(id)arg1 andNewURL:(id)arg2;
- (void)praseM3U8Finished:(id)arg1;
- (void)praseM3U8Failed:(id)arg1;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)getQualityArray:(id)arg1 andChosenQuality:(id)arg2;
- (id)handleTheTextForData:(id)arg1;
- (void)loadUrl:(id)arg1 sourceId:(long long)arg2;
- (void)requestVideoDataWithVideoId:(long long)arg1 andSourceId:(long long)arg2 andNumber:(long long)arg3 downloadModel:(id)arg4;
- (void)requestVarityWebUrlWithSectionId:(long long)arg1 andSourceId:(long long)arg2 downloadModel:(id)arg3;
- (void)prepareToPraserModel:(id)arg1 complete:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

