//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMHomeView.h"

@class LZMBaseADView, UIImageView, UILabel;

@interface LZMFHomeAdPageView : LZMHomeView
{
    UIImageView *_BGImageView;
    UILabel *_titleLab;
    UILabel *_descLabel;
    LZMBaseADView *_baseADView;
}

@property(retain, nonatomic) LZMBaseADView *baseADView; // @synthesize baseADView=_baseADView;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *BGImageView; // @synthesize BGImageView=_BGImageView;
- (void).cxx_destruct;

@end

