//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMHomeView.h"

@class NSMutableArray, NSString;

@interface LZMHomeVerticalView : LZMHomeView
{
    _Bool _isLastPage;
    NSMutableArray *_dataArray;
    NSString *_backGroundTimeCase;
    NSMutableArray *_exChangeArr;
}

@property(retain, nonatomic) NSMutableArray *exChangeArr; // @synthesize exChangeArr=_exChangeArr;
@property(nonatomic) _Bool isLastPage; // @synthesize isLastPage=_isLastPage;
@property(copy, nonatomic) NSString *backGroundTimeCase; // @synthesize backGroundTimeCase=_backGroundTimeCase;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (void)addModelForDataArray;
- (void)exchangeArrReady:(long long)arg1;
- (_Bool)getBackGroudTimeReSet;
- (void)footerExchangeAction:(id)arg1;
- (void)failedReloadBtnAction:(id)arg1;
- (void)footerMoreButtonAction:(id)arg1;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)requestVieoFreashData:(id)arg1;
- (void)requsetBeautyLiveData;
- (void)requestCurrentTypeData:(long long)arg1 andCurrentURL:(id)arg2;
- (void)setType:(long long)arg1;
- (void)setFrame:(struct CGRect)arg1;

@end

