//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LZMAdBaseManager.h"

#import "InfoFlowSDKDelegate.h"
#import "SplashSDKDelegate.h"
#import "SpotSDKDelegate.h"

@class InfoFlowSDK, InfoFlowView, NSString, SplashSDK, SpotSDK, UIView;

@interface LZMJuShaManager : LZMAdBaseManager <SplashSDKDelegate, InfoFlowSDKDelegate, SpotSDKDelegate>
{
    SplashSDK *_splash;
    SpotSDK *_spotSDK;
    UIView *_interBGView;
    InfoFlowSDK *_curNativeAd;
    long long _curNaAdPlaceId;
    InfoFlowView *_prollAd;
    long long _prollOretion;
}

+ (id)sharedInstance;
@property(nonatomic) long long prollOretion; // @synthesize prollOretion=_prollOretion;
@property(retain, nonatomic) InfoFlowView *prollAd; // @synthesize prollAd=_prollAd;
@property(nonatomic) long long curNaAdPlaceId; // @synthesize curNaAdPlaceId=_curNaAdPlaceId;
@property(retain, nonatomic) InfoFlowSDK *curNativeAd; // @synthesize curNativeAd=_curNativeAd;
@property(retain, nonatomic) UIView *interBGView; // @synthesize interBGView=_interBGView;
@property(retain, nonatomic) SpotSDK *spotSDK; // @synthesize spotSDK=_spotSDK;
@property(retain, nonatomic) SplashSDK *splash; // @synthesize splash=_splash;
- (void).cxx_destruct;
- (void)clickSpot:(id)arg1;
- (void)closeSpot:(id)arg1;
- (void)failToFetchSpot:(id)arg1 error:(id)arg2;
- (void)successToFetchSpot:(id)arg1;
- (void)startInterstitialAd:(id)arg1 inRect:(struct CGRect)arg2;
- (void)prollBackAppNow;
- (void)clickInfoFlow:(id)arg1;
- (void)failToFetchInfoFlow:(id)arg1 error:(id)arg2;
- (void)successToFetchInfoFlow:(id)arg1 views:(id)arg2;
- (id)getPlaceIdFormCurrentNative:(id)arg1;
- (void)prollAdTimeOutAction;
- (void)backBtnClick:(id)arg1;
- (void)addBackBtnAndTimeLabel:(id)arg1;
- (void)activeProllAdBaseBiew:(id)arg1 withObject:(id)arg2 andPlaceId:(long long)arg3 andADtype:(long long)arg4;
- (void)activeNativeAdBaseBiew:(id)arg1 withObject:(id)arg2 andPlaceId:(long long)arg3 andADtype:(long long)arg4;
- (void)startNativeAd:(long long)arg1;
- (void)removeCurrentAdORStopAd:(id)arg1;
- (void)failToFetchSplash:(id)arg1 error:(id)arg2;
- (void)successToFetchSplash:(id)arg1 drawFrame:(struct CGRect)arg2;
- (void)clickSplash:(id)arg1;
- (void)closeSplash:(id)arg1;
- (void)startSplashAd;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

