//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class LZMImageView, UIButton;

@interface LZMNotificationAgainView : UIView
{
    LZMImageView *_backgroundView;
    UIButton *_cancelButton;
    UIButton *_settingButton;
}

@property(retain, nonatomic) UIButton *settingButton; // @synthesize settingButton=_settingButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) LZMImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (void)notificationViewSettingButtonAction:(id)arg1;
- (void)notificationViewCancelButtonAction:(id)arg1;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

