//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMVideoPartModel, UIImageView, UILabel;

@interface LZMNumberCell : UICollectionViewCell
{
    LZMVideoPartModel *_model;
    UILabel *_titleLabel;
    UIImageView *_downloadStateImage;
}

@property(retain, nonatomic) UIImageView *downloadStateImage; // @synthesize downloadStateImage=_downloadStateImage;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) LZMVideoPartModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

