//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class LZMImageView, LZMVideoModel, UIImageView, UILabel;

@interface LZMSearchVideoCell : UITableViewCell
{
    LZMVideoModel *_videoModel;
    LZMImageView *_iconImageView;
    UIImageView *_trailerImageView;
    UILabel *_nameLabel;
    UILabel *_videoTypeLabel;
    UILabel *_detailLabel;
}

@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *videoTypeLabel; // @synthesize videoTypeLabel=_videoTypeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *trailerImageView; // @synthesize trailerImageView=_trailerImageView;
@property(retain, nonatomic) LZMImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) LZMVideoModel *videoModel; // @synthesize videoModel=_videoModel;
- (void).cxx_destruct;
- (void)buildUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

