//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YYModel.h"

@class NSArray, NSString;

@interface LZMSearchModel : NSObject <YYModel>
{
    NSArray *_movie;
    NSArray *_drama;
    NSArray *_shows;
    NSArray *_comic;
    NSArray *_records;
    NSArray *_children;
    NSArray *_channels;
    NSArray *_plays;
    NSArray *_short_video;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *short_video; // @synthesize short_video=_short_video;
@property(retain, nonatomic) NSArray *plays; // @synthesize plays=_plays;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
@property(retain, nonatomic) NSArray *records; // @synthesize records=_records;
@property(retain, nonatomic) NSArray *comic; // @synthesize comic=_comic;
@property(retain, nonatomic) NSArray *shows; // @synthesize shows=_shows;
@property(retain, nonatomic) NSArray *drama; // @synthesize drama=_drama;
@property(retain, nonatomic) NSArray *movie; // @synthesize movie=_movie;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

