//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMImageView, LZMVideoModel, YYLabel;

@interface LZMVideoRecommendCell : UICollectionViewCell
{
    LZMVideoModel *_model;
    LZMImageView *_coverImageView;
    YYLabel *_titleLabel;
    YYLabel *_viewCountLabel;
    LZMImageView *_backgroundImgView;
    LZMImageView *_trailerView;
}

@property(retain, nonatomic) LZMImageView *trailerView; // @synthesize trailerView=_trailerView;
@property(retain, nonatomic) LZMImageView *backgroundImgView; // @synthesize backgroundImgView=_backgroundImgView;
@property(retain, nonatomic) YYLabel *viewCountLabel; // @synthesize viewCountLabel=_viewCountLabel;
@property(retain, nonatomic) YYLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) LZMImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) LZMVideoModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

