//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class LZMLiveUrlModel, UILabel;

@interface LZMWebSourceCell : UICollectionViewCell
{
    LZMLiveUrlModel *_sourceModel;
    UILabel *_nameLabel;
    UILabel *_urlLabel;
}

@property(retain, nonatomic) UILabel *urlLabel; // @synthesize urlLabel=_urlLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) LZMLiveUrlModel *sourceModel; // @synthesize sourceModel=_sourceModel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

