//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString, UIButton, UICollectionView, YYLabel;

@interface LZMWebUrlChooseView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate>
{
    CDUnknownBlockType _changeSourceBlock;
    NSMutableArray *_sourceList;
    UIView *_bearView;
    YYLabel *_titleLabel;
    UICollectionView *_collectionView;
    UIButton *_cancelButton;
    double _bearViewHeight;
}

@property(nonatomic) double bearViewHeight; // @synthesize bearViewHeight=_bearViewHeight;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) YYLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *bearView; // @synthesize bearView=_bearView;
@property(retain, nonatomic) NSMutableArray *sourceList; // @synthesize sourceList=_sourceList;
@property(copy, nonatomic) CDUnknownBlockType changeSourceBlock; // @synthesize changeSourceBlock=_changeSourceBlock;
- (void).cxx_destruct;
- (void)chooseIndex:(long long)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)tapGestureRecognizer;
- (void)cancelButtonnAction:(id)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)addTapGesture;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1 sourceInfoArray:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

