//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface LZMYuStreamModel : NSObject
{
    long long _err_code;
    NSArray *_data;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(nonatomic) long long err_code; // @synthesize err_code=_err_code;
- (void).cxx_destruct;

@end

