//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton;

@interface LZMYAddChannelCell : UITableViewCell
{
    CDUnknownBlockType _addVideoBlock;
    UIButton *_addVideoBtn;
}

@property(retain, nonatomic) UIButton *addVideoBtn; // @synthesize addVideoBtn=_addVideoBtn;
@property(copy, nonatomic) CDUnknownBlockType addVideoBlock; // @synthesize addVideoBlock=_addVideoBlock;
- (void).cxx_destruct;
- (void)addVideo;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

