//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshAutoStateFooter.h"

@class UIActivityIndicatorView;

@interface MJRefreshAutoNormalFooter : MJRefreshAutoStateFooter
{
    long long _activityIndicatorViewStyle;
    UIActivityIndicatorView *_loadingView;
}

@property(nonatomic) __weak UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle=_activityIndicatorViewStyle;
- (void).cxx_destruct;
- (void)setState:(long long)arg1;
- (void)placeSubviews;
- (void)prepare;

@end

