//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MOBFNotificationCenter : NSObject
{
}

+ (void)_setupCrashLogMonitor;
+ (void)_appDidFinishedLaunching:(id)arg1;
+ (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
+ (void)removeObserver:(id)arg1;
+ (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
+ (void)load;

@end

