//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTBaseParser : NSObject
{
}

- (id)uuidString;
- (id)convert2Base64:(id)arg1;
- (id)format:(id)arg1 withDic:(id)arg2;

@end

