//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (YSCBGModel)
+ (_Bool)YSCBG_clearDictionary;
+ (_Bool)YSCBG_removeValueForKey:(id)arg1;
+ (id)YSCBG_valueForKey:(id)arg1;
+ (void)YSCBG_enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;
+ (_Bool)YSCBG_updateValue:(id)arg1 forKey:(id)arg2;
+ (_Bool)YSCBG_setValue:(id)arg1 forKey:(id)arg2;
- (_Bool)YSCBG_saveDictionary;
@end

