//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (TVEModel)
+ (id)tve_modelsWithKeyValues:(id)arg1;
+ (id)tve_modelWithKeyValueString:(id)arg1;
+ (id)tve_modelWithKeyValue:(id)arg1;
- (id)tve_modelsToKeyValues;
- (id)tve_modelToKeyValue;
- (id)tve_initWithKeyValues:(id)arg1;
- (Class)tve_getAttributeClass:(id)arg1;
- (_Bool)tve_isSystemClass:(id)arg1;
- (void)tve_setKey:(id)arg1 withValue:(id)arg2;
- (id)tve_initWithKeyValue:(id)arg1;
- (Class)tve_getPropertyClass:(id)arg1;
- (id)tve_getJsonKey:(id)arg1;
@end

