//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (Property)
+ (void)mj_setupReplacedKeyFromPropertyName121:(CDUnknownBlockType)arg1;
+ (void)mj_setupReplacedKeyFromPropertyName:(CDUnknownBlockType)arg1;
+ (void)mj_setupObjectClassInArray:(CDUnknownBlockType)arg1;
+ (id)mj_getNewValueFromObject:(id)arg1 oldValue:(id)arg2 property:(id)arg3;
+ (void)mj_setupNewValueFromOldValue:(CDUnknownBlockType)arg1;
+ (id)properties;
+ (void)mj_enumerateProperties:(CDUnknownBlockType)arg1;
+ (Class)propertyObjectClassInArray:(id)arg1;
+ (id)propertyKey:(id)arg1;
+ (id)dictForKey:(const void *)arg1;
+ (void)load;
@end

