//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (MJPropertyDeprecated_v_2_5_16)
+ (void)setupObjectClassInArray:(CDUnknownBlockType)arg1;
+ (void)setupReplacedKeyFromPropertyName121:(CDUnknownBlockType)arg1;
+ (void)setupReplacedKeyFromPropertyName:(CDUnknownBlockType)arg1;
+ (id)getNewValueFromObject:(id)arg1 oldValue:(id)arg2 property:(id)arg3;
+ (void)setupNewValueFromOldValue:(CDUnknownBlockType)arg1;
+ (void)enumerateProperties:(CDUnknownBlockType)arg1;
@end

