//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface P2PSdk : NSObject
{
}

+ (void)networkChanged:(id)arg1;
+ (void)config;
+ (id)getStatistics;
+ (unsigned int)getPosition;
+ (void)unloadContent;
+ (void)loadVideoWithType:(int)arg1 Stream:(id)arg2 video:(id)arg3 p2p:(id)arg4 url:(id)arg5 cdn:(id)arg6 time:(double)arg7 result:(CDUnknownBlockType)arg8;
+ (void)loadVideoWithType:(int)arg1 Stream:(id)arg2 video:(id)arg3 p2p:(id)arg4 url:(id)arg5 cdn:(id)arg6 result:(CDUnknownBlockType)arg7;
+ (void)setEventHandler:(id)arg1;
+ (void)initSDKWithClinetId:(id)arg1 clientKey:(id)arg2 bundleId:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;

@end

