//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTDataCache : NSObject
{
}

+ (id)shareDataCache;
- (void)removeClassifyCacheWithClassify:(id)arg1;
- (id)getKBorMBorGBWith:(double)arg1;
- (double)getCacheSizeWithClassify:(id)arg1;
- (double)getCacheSizeWithCacheFilePath:(id)arg1;
- (long long)fileSizeAtPath:(id)arg1;
- (id)getDataForDocumentWithDataName:(id)arg1 Classify:(id)arg2;
- (void)saveDataForDocumentWithData:(id)arg1 DataName:(id)arg2 Classify:(id)arg3;
- (id)documentFileManagerPathWithFileName:(id)arg1 Classify:(id)arg2;
- (id)getDocumentFileManagerPathWithClassify:(id)arg1;
- (id)documentPath;

@end

