//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSSet, NSString;

@interface TDAACodeless : NSObject
{
    _Bool _isDebugging;
    NSString *_nameTag;
    NSString *_distinctId;
    NSString *_apiToken;
    NSObject<OS_dispatch_queue> *_serialQueue;
    id _designerConnection;
    NSSet *_eventBindings;
    NSString *_switchboardURL;
}

+ (void)assertPropertyTypes:(id)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceWithToken:(id)arg1;
@property(copy) NSString *switchboardURL; // @synthesize switchboardURL=_switchboardURL;
@property(retain, nonatomic) NSSet *eventBindings; // @synthesize eventBindings=_eventBindings;
@property(retain, nonatomic) id designerConnection; // @synthesize designerConnection=_designerConnection;
@property(nonatomic) _Bool isDebugging; // @synthesize isDebugging=_isDebugging;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(copy, nonatomic) NSString *apiToken; // @synthesize apiToken=_apiToken;
@property(readonly, copy) NSString *distinctId; // @synthesize distinctId=_distinctId;
@property(copy) NSString *nameTag; // @synthesize nameTag=_nameTag;
- (void).cxx_destruct;
- (id)pinnedCertificates;
- (void)addTestDevice:(id)arg1;
- (void)executeCachedEventBindings;
- (void)connectToDesigner:(_Bool)arg1;
- (void)updataEventBindings:(id)arg1;
- (id)filterRepetitionItem:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)setUpListeners;
- (id)sdkVersion;
- (void)unarchiveEventBindings;
- (id)unarchiveFromFile:(id)arg1;
- (void)unarchive;
- (void)archiveEventBindings;
- (void)archive;
- (id)eventBindingsFilePath;
- (id)filePathForData:(id)arg1;
- (void)track:(id)arg1 properties:(id)arg2;
- (void)dealloc;
- (id)initWithToken:(id)arg1;

@end

