//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TDAANetworkInfo : NSObject
{
}

+ (id)getDataCounters;
+ (id)getEn0Mac;
+ (id)getAllMacs;
+ (void)justPing:(const char *)arg1;
+ (id)convertIPToMac:(id)arg1;
+ (id)getCellularIPAddress;
+ (id)getWifiIPAddress;
+ (id)getIPAddress:(const char *)arg1;
+ (id)getRouterSSID;
+ (id)getRouterBSSID;
+ (id)getRouterInfo:(id)arg1;

@end

