//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDAABaseModel.h"

@class TDAADeviceHardwareConfig, TDAADeviceId, TDAADeviceSoftwareConfig, TDAARuntimeConfig;

@interface TDAADevice : TDAABaseModel
{
    TDAADeviceId *_deviceId;
    TDAADeviceHardwareConfig *_hardwareConfig;
    TDAADeviceSoftwareConfig *_softwareConfig;
    TDAARuntimeConfig *_runtimeConfig;
}

@property(retain, nonatomic) TDAARuntimeConfig *runtimeConfig; // @synthesize runtimeConfig=_runtimeConfig;
@property(retain, nonatomic) TDAADeviceSoftwareConfig *softwareConfig; // @synthesize softwareConfig=_softwareConfig;
@property(retain, nonatomic) TDAADeviceHardwareConfig *hardwareConfig; // @synthesize hardwareConfig=_hardwareConfig;
@property(retain, nonatomic) TDAADeviceId *deviceId; // @synthesize deviceId=_deviceId;
- (void).cxx_destruct;
- (id)archiveToDictionary;

@end

