//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TaobaoCipher;

@interface TVECMSManager : NSObject
{
    TaobaoCipher *_cipher;
}

+ (id)urlWithPath:(id)arg1 parameters:(id)arg2;
+ (id)signParameters:(id)arg1 key:(id)arg2;
+ (id)defaultParameters;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) TaobaoCipher *cipher; // @synthesize cipher=_cipher;
- (void).cxx_destruct;
- (void)initTaoBaoCipher;
- (void)fetchPageDataWithPageId:(id)arg1 Success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchAdConfigDataSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchCurrentTimeSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchEPGLists:(id)arg1 date:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)fetchCurrentEPGs:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchEPGList:(long long)arg1 date:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)fetchCurrentEPG:(long long)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchIPAreaSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchVideo:(long long)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchVideoListWithCategory:(long long)arg1 tags:(id)arg2 limit:(long long)arg3 offset:(long long)arg4 order:(id)arg5 sort:(id)arg6 success:(CDUnknownBlockType)arg7 failure:(CDUnknownBlockType)arg8;
- (void)fetchCategoryTag:(long long)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchCategoryOrder:(id)arg1 sort:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)fetchStramListSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchSingleStreamPlayUrlsWithChannelId:(long long)arg1 Success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchStreamPlayUrlsSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchPlayUrl:(long long)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)fetchConfigSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)requestWithMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
@property(readonly, copy, nonatomic) NSString *cmsBaseURL;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

