//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVEBaseModel.h"

@class NSArray, NSString;

@interface TVEFeed : TVEBaseModel
{
    NSString *_ID;
    long long _content_type;
    long long _content_id;
    NSString *_url;
    NSString *_title;
    NSString *_thumb_x;
    NSArray *_epgs;
    NSString *_bind_id;
    NSString *_sort;
    NSString *_score;
    NSString *_vip_only;
    NSString *_limited_free;
    NSString *_released_at;
    NSString *_expired_at;
    NSString *_published_at;
    NSString *_provider_id;
    NSString *_recommend;
    NSString *_thumb_y;
    NSString *_recommreleased_atend;
}

+ (id)tve_objectClassInArray;
@property(copy, nonatomic) NSString *recommreleased_atend; // @synthesize recommreleased_atend=_recommreleased_atend;
@property(copy, nonatomic) NSString *thumb_y; // @synthesize thumb_y=_thumb_y;
@property(copy, nonatomic) NSString *recommend; // @synthesize recommend=_recommend;
@property(copy, nonatomic) NSString *provider_id; // @synthesize provider_id=_provider_id;
@property(copy, nonatomic) NSString *published_at; // @synthesize published_at=_published_at;
@property(copy, nonatomic) NSString *expired_at; // @synthesize expired_at=_expired_at;
@property(copy, nonatomic) NSString *released_at; // @synthesize released_at=_released_at;
@property(copy, nonatomic) NSString *limited_free; // @synthesize limited_free=_limited_free;
@property(copy, nonatomic) NSString *vip_only; // @synthesize vip_only=_vip_only;
@property(copy, nonatomic) NSString *score; // @synthesize score=_score;
@property(copy, nonatomic) NSString *sort; // @synthesize sort=_sort;
@property(copy, nonatomic) NSString *bind_id; // @synthesize bind_id=_bind_id;
@property(retain, nonatomic) NSArray *epgs; // @synthesize epgs=_epgs;
@property(copy, nonatomic) NSString *thumb_x; // @synthesize thumb_x=_thumb_x;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long content_id; // @synthesize content_id=_content_id;
@property(nonatomic) long long content_type; // @synthesize content_type=_content_type;
@property(nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

