//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (WBSDKResize)
- (id)wbsdk_resizedImageWithCompressionLevelHighResolution;
- (struct CGAffineTransform)wbsdk_transformForOrientation:(struct CGSize)arg1;
- (id)wbsdk_resizedImage:(struct CGSize)arg1 transform:(struct CGAffineTransform)arg2 drawTransposed:(_Bool)arg3 interpolationQuality:(int)arg4;
- (id)wbsdk_resizedImageWithContentMode:(long long)arg1 bounds:(struct CGSize)arg2 interpolationQuality:(int)arg3;
- (id)wbsdk_resizedImage:(struct CGSize)arg1 interpolationQuality:(int)arg2;
@end

