//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (helper)
+ (double)percentAngle:(double)arg1 betweenStart:(double)arg2 end:(double)arg3 clockwise:(_Bool)arg4;
+ (id)buildAngularGradientInRect:(struct CGRect)arg1 radius:(double)arg2 startAngle:(double)arg3 endAngle:(double)arg4 startColor:(id)arg5 endColor:(id)arg6 clockwise:(_Bool)arg7 scale:(double)arg8;
+ (id)buildAngularGradientInRect:(struct CGRect)arg1 radius:(double)arg2 startDegree:(double)arg3 endDegree:(double)arg4 startColor:(id)arg5 endColor:(id)arg6 clockwise:(_Bool)arg7 scale:(double)arg8;
+ (id)pngImageWithFileName:(id)arg1;
+ (id)jpgImageWithFileName:(id)arg1;
+ (id)createRoundedRectImage:(id)arg1 size:(struct CGSize)arg2 radius:(double)arg3;
+ (id)imageWithColor:(id)arg1 andSize:(struct CGSize)arg2 andRadius:(float)arg3;
+ (id)imageWithColor:(id)arg1 andSize:(struct CGSize)arg2;
- (id)imageWithRoundedCornersRadius:(float)arg1;
- (id)blurryCoreImageWithBlurLevel:(double)arg1;
- (id)blurryImageWithBlurLevel:(double)arg1;
- (id)imageWithTintColor:(id)arg1 blendMode:(int)arg2;
- (id)imageWithGradientTintColor:(id)arg1;
- (id)imageWithTintColor:(id)arg1;
- (id)imageRotatedByDegrees:(double)arg1;
- (id)imageRotatedByRadians:(double)arg1;
- (id)imageByScalingToSize:(struct CGSize)arg1;
- (id)imageByScalingProportionallyToSize:(struct CGSize)arg1;
- (id)imageByScalingProportionallyToMinimumSize:(struct CGSize)arg1;
- (id)imageAtRect:(struct CGRect)arg1;
@end

