//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MASViewAttribute;

@interface UIViewController (MASAdditions)
@property(readonly, nonatomic) MASViewAttribute *mas_bottomLayoutGuideBottom;
@property(readonly, nonatomic) MASViewAttribute *mas_bottomLayoutGuideTop;
@property(readonly, nonatomic) MASViewAttribute *mas_bottomLayoutGuide;
@property(readonly, nonatomic) MASViewAttribute *mas_topLayoutGuideBottom;
@property(readonly, nonatomic) MASViewAttribute *mas_topLayoutGuideTop;
@property(readonly, nonatomic) MASViewAttribute *mas_topLayoutGuide;
@end

