//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (WebCache)
- (void)gdtsd_removeActivityIndicator;
- (void)gdtsd_addActivityIndicator;
- (int)gdtsd_getIndicatorStyle;
- (void)gdtsd_setIndicatorStyle:(long long)arg1;
- (_Bool)gdtsd_showActivityIndicatorView;
- (void)gdtsd_setShowActivityIndicatorView:(_Bool)arg1;
- (void)setActivityIndicator:(id)arg1;
- (id)activityIndicator;
- (void)gdtsd_setNeedsLayout;
- (void)gdtsd_setImage:(id)arg1 imageData:(id)arg2 basedOnClassOrViaCustomSetImageBlock:(CDUnknownBlockType)arg3;
- (void)gdtsd_cancelCurrentImageLoad;
- (void)gdtsd_internalSetImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 operationKey:(id)arg4 setImageBlock:(CDUnknownBlockType)arg5 progress:(CDUnknownBlockType)arg6 completed:(CDUnknownBlockType)arg7 context:(id)arg8;
- (void)gdtsd_internalSetImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 operationKey:(id)arg4 setImageBlock:(CDUnknownBlockType)arg5 progress:(CDUnknownBlockType)arg6 completed:(CDUnknownBlockType)arg7;
- (id)gdtsd_imageURL;
@end

