//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMANBaseEvent.h"

@class NSMutableDictionary, NSString;

@interface UMADplus : UMANBaseEvent
{
    NSString *_id;
    NSMutableDictionary *_values;
    NSMutableDictionary *dplusDic;
    NSMutableDictionary *dplusPreDic;
}

+ (int)rowCountInTable;
+ (id)filterValidArray:(id)arg1 containInOrgArray:(id)arg2;
+ (id)filterValidArrayValueWithFirstLaunchEvent:(id)arg1;
+ (id)truncateFirstLaunchEventStringKey:(id)arg1;
+ (id)prePropertyFilter:(id)arg1;
+ (id)propertyFilter:(id)arg1;
+ (id)filterValidArrayValueWithValueArray:(id)arg1;
+ (_Bool)checkValidArrayValue:(id)arg1;
+ (_Bool)checkValidNumberValue:(id)arg1;
+ (_Bool)checkValidStringValue:(id)arg1;
+ (_Bool)checkValidKey:(id)arg1 type:(id)arg2;
+ (id)truncateValueStringKey:(id)arg1;
+ (id)truncateStringKey:(id)arg1;
+ (id)sharedInstance;
@property(retain) NSMutableDictionary *dplusPreDic; // @synthesize dplusPreDic;
@property(retain) NSMutableDictionary *dplusDic; // @synthesize dplusDic;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (void)dplusWriteToFile:(id)arg1;
- (void)setFirstLaunchEvent:(id)arg1;
- (void)megerImpintAndLocalForFirstLaunch;
- (void)track:(id)arg1 property:(id)arg2;
- (void)clearPreProperties;
- (void)clearSuperProperties;
- (id)getPreProperties;
- (id)getSuperProperties;
- (id)getSuperProperty:(id)arg1;
- (void)unregisterPreProperty:(id)arg1;
- (void)unregisterSuperProperty:(id)arg1;
- (void)registerPreProperties:(id)arg1;
- (void)registerSuperProperty:(id)arg1;
- (id)init;

@end

