//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMUShareCommonModel.h"

@class NSString;

@interface UMCommonAuthModel : UMUShareCommonModel
{
    NSString *_pf;
    NSString *_sdkt;
    NSString *_am;
    NSString *_uid;
    NSString *_aid;
    NSString *_as;
    NSString *_at;
    NSString *_unionid;
    NSString *_tag;
}

@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *unionid; // @synthesize unionid=_unionid;
@property(retain, nonatomic) NSString *at; // @synthesize at=_at;
@property(retain, nonatomic) NSString *as; // @synthesize as=_as;
@property(retain, nonatomic) NSString *aid; // @synthesize aid=_aid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSString *am; // @synthesize am=_am;
@property(retain, nonatomic) NSString *sdkt; // @synthesize sdkt=_sdkt;
@property(retain, nonatomic) NSString *pf; // @synthesize pf=_pf;
- (void).cxx_destruct;
- (id)description;
- (void)generateDeleteSQLWithSQLStringArray:(id)arg1 withSQLColumnValueArray:(id)arg2;
- (void)generateSaveSQLWithSQLStringArray:(id)arg1 withSQLColumnValueArray:(id)arg2;
- (void)parseDictionary:(id)arg1;
- (id)toSQLMappedDictionary;
- (id)toDictionary;

@end

