//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMHelper : NSObject
{
}

+ (_Bool)isCheckVersion:(id)arg1;
+ (id)preVersions:(id)arg1;
+ (double)elapsedTimeFromPost;
+ (_Bool)defconPass;
+ (_Bool)isOverSeas;
+ (_Bool)checkIsOverseas;
+ (id)dplusEventsPath;
+ (id)dplusPreFilePath;
+ (id)dplusSuperFilePath;
+ (id)trimUTF8String:(id)arg1 toByteLen:(long long)arg2;
+ (_Bool)checkU48Character:(id)arg1;
+ (unsigned long long)UTCTimeIntervalMS;
+ (id)arrayToAgStr:(id)arg1;
+ (id)appVersionString;
+ (id)sdkVersionString;
+ (_Bool)isDebugging;

@end

