//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMShareObject.h"

@class NSArray;

@interface UMShareImageObject : UMShareObject
{
    id _shareImage;
    NSArray *_shareImageArray;
}

+ (id)shareObjectWithTitle:(id)arg1 descr:(id)arg2 thumImage:(id)arg3;
@property(copy, nonatomic) NSArray *shareImageArray; // @synthesize shareImageArray=_shareImageArray;
@property(retain, nonatomic) id shareImage; // @synthesize shareImage=_shareImage;
- (void).cxx_destruct;

@end

