//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMSocialCharacterUtilityForSina : NSObject
{
}

+ (_Bool)UMSocial_IsEmoji:(id)arg1;
+ (_Bool)UMSocial_IsChinese:(id)arg1;
+ (_Bool)UMSocial_IsAscii:(id)arg1;
+ (_Bool)doIsAscii:(int)arg1;

@end

