//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialShareObjectConfig.h"

@interface UMSocialShareMusicObjectConfig : UMSocialShareObjectConfig
{
    unsigned long long _musicUrlLimit;
    unsigned long long _musicLowBandUrlLimit;
    unsigned long long _musicDataUrlLimit;
    unsigned long long _musicLowBandDataUrlLimit;
}

@property(nonatomic) unsigned long long musicLowBandDataUrlLimit; // @synthesize musicLowBandDataUrlLimit=_musicLowBandDataUrlLimit;
@property(nonatomic) unsigned long long musicDataUrlLimit; // @synthesize musicDataUrlLimit=_musicDataUrlLimit;
@property(nonatomic) unsigned long long musicLowBandUrlLimit; // @synthesize musicLowBandUrlLimit=_musicLowBandUrlLimit;
@property(nonatomic) unsigned long long musicUrlLimit; // @synthesize musicUrlLimit=_musicUrlLimit;

@end

