//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialShareObjectConfig.h"

@interface UMSocialShareExtendObjectConfig : UMSocialShareObjectConfig
{
    unsigned long long _urlLimit;
    unsigned long long _extInfoLimit;
    unsigned long long _fileDataLimit;
}

@property(nonatomic) unsigned long long fileDataLimit; // @synthesize fileDataLimit=_fileDataLimit;
@property(nonatomic) unsigned long long extInfoLimit; // @synthesize extInfoLimit=_extInfoLimit;
@property(nonatomic) unsigned long long urlLimit; // @synthesize urlLimit=_urlLimit;

@end

