//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialWechatHandler.h"

#import "WXApiDelegate.h"

@class NSString;

@interface UMSocialOfficialWechatHandler : UMSocialWechatHandler <WXApiDelegate>
{
}

+ (id)defaultManager;
+ (void)load;
- (void)onResp:(id)arg1;
- (_Bool)sendShareRequest:(id)arg1 withType:(unsigned long long)arg2;
- (_Bool)sendAuthRequest;
- (_Bool)handleOpenURL:(id)arg1;
- (id)umSocial_PlatformSDKVersion;
- (_Bool)umSocial_isSupport;
- (_Bool)umSocial_isInstall;
- (void)umSocial_setAppKey:(id)arg1 withAppSecret:(id)arg2 withRedirectURL:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

