//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface UMSocialPlatformItemViewConfig : NSObject
{
    UIColor *_sharePlatformItemViewBGRadiusColor;
    UIColor *_sharePlatformItemViewBGRadiusColorPressed;
    UIColor *_sharePlatformItemViewPlatformNameColor;
}

@property(retain, nonatomic) UIColor *sharePlatformItemViewPlatformNameColor; // @synthesize sharePlatformItemViewPlatformNameColor=_sharePlatformItemViewPlatformNameColor;
@property(retain, nonatomic) UIColor *sharePlatformItemViewBGRadiusColorPressed; // @synthesize sharePlatformItemViewBGRadiusColorPressed=_sharePlatformItemViewBGRadiusColorPressed;
@property(retain, nonatomic) UIColor *sharePlatformItemViewBGRadiusColor; // @synthesize sharePlatformItemViewBGRadiusColor=_sharePlatformItemViewBGRadiusColor;
- (void).cxx_destruct;

@end

