//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMSocialUIUtility : NSObject
{
}

+ (id)imageNamed:(id)arg1;
+ (id)localizedString:(id)arg1 defaultString:(id)arg2;
+ (void)configWithPlatformType:(long long)arg1 withImageName:(id *)arg2 withPlatformName:(id *)arg3;
+ (id)gBundle;
+ (id)colorWithHexString:(id)arg1;

@end

