//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialQQHandler.h"

#import "QQApiInterfaceDelegate.h"
#import "TencentSessionDelegate.h"
#import "UMSocialPlatformProvider.h"

@class NSString, TencentOAuth;

@interface UMSocialOfficialQQHandler : UMSocialQQHandler <QQApiInterfaceDelegate, TencentSessionDelegate, UMSocialPlatformProvider>
{
    TencentOAuth *_tencentOAuth;
}

+ (id)defaultManager;
+ (void)load;
@property(retain, nonatomic) TencentOAuth *tencentOAuth; // @synthesize tencentOAuth=_tencentOAuth;
- (void).cxx_destruct;
- (void)onResp:(id)arg1;
- (void)shareQQSendObject:(id)arg1;
- (void)sendMessage:(unsigned long long)arg1 message:(id)arg2;
- (int)sendShareRequest:(id)arg1 withType:(unsigned long long)arg2 andUserInfo:(id)arg3;
- (void)tencentDidLogout;
- (void)tencentDidNotNetWork;
- (void)tencentDidNotLogin:(_Bool)arg1;
- (void)tencentDidLogin;
- (void)getUserInfoResponse:(id)arg1;
- (_Bool)sendUserInfoRequest:(id)arg1;
- (void)sendCancelAuth;
- (_Bool)sendAuthRequest:(id)arg1 appId:(id)arg2 safari:(_Bool)arg3;
- (_Bool)handleOpenURL:(id)arg1;
- (id)umSocial_PlatformSDKVersion;
- (_Bool)umSocial_isSupport;
- (_Bool)umSocial_isInstall;
- (void)umSocial_setAppKey:(id)arg1 withAppSecret:(id)arg2 withRedirectURL:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long socialPlatformType;
@property(readonly) Class superclass;

@end

