//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XHImageCache : NSObject
{
}

+ (id)xh_md5String:(id)arg1;
+ (void)xh_addDoNotBackupAttribute:(id)arg1;
+ (void)xh_createBaseDirectoryAtPath:(id)arg1;
+ (void)xh_checkDirectory:(id)arg1;
+ (_Bool)xh_checkFile:(id)arg1;
+ (id)xh_cacheImagePath;
+ (void)xh_saveImageData:(id)arg1 imageURL:(id)arg2;
+ (id)xh_getCacheImageWithURL:(id)arg1;

@end

