//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableSet, YSCImageCache, YSCWebImageDownloader;

@interface YSCWebImageManager : NSObject
{
    id <YSCWebImageManagerDelegate> _delegate;
    YSCImageCache *_imageCache;
    YSCWebImageDownloader *_imageDownloader;
    CDUnknownBlockType _cacheKeyFilter;
    NSMutableSet *_failedURLs;
    NSMutableArray *_runningOperations;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *runningOperations; // @synthesize runningOperations=_runningOperations;
@property(retain, nonatomic) NSMutableSet *failedURLs; // @synthesize failedURLs=_failedURLs;
@property(copy, nonatomic) CDUnknownBlockType cacheKeyFilter; // @synthesize cacheKeyFilter=_cacheKeyFilter;
@property(retain, nonatomic) YSCWebImageDownloader *imageDownloader; // @synthesize imageDownloader=_imageDownloader;
@property(retain, nonatomic) YSCImageCache *imageCache; // @synthesize imageCache=_imageCache;
@property(nonatomic) __weak id <YSCWebImageManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)callCompletionBlockForOperation:(id)arg1 completion:(CDUnknownBlockType)arg2 image:(id)arg3 data:(id)arg4 error:(id)arg5 cacheType:(long long)arg6 finished:(_Bool)arg7 url:(id)arg8;
- (void)callCompletionBlockForOperation:(id)arg1 completion:(CDUnknownBlockType)arg2 error:(id)arg3 url:(id)arg4;
- (void)safelyRemoveOperationFromRunning:(id)arg1;
- (_Bool)isRunning;
- (void)cancelAll;
- (void)saveImageToCache:(id)arg1 forURL:(id)arg2;
- (id)loadImageWithURL:(id)arg1 options:(unsigned long long)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;
- (void)diskImageExistsForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cachedImageExistsForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)scaledImageForKey:(id)arg1 image:(id)arg2;
- (id)cacheKeyForURL:(id)arg1;
- (id)initWithCache:(id)arg1 downloader:(id)arg2;
- (id)init;

@end

